export const FORM_ACTIONS = {
  // Form-level actions
  SET_FORM_SETTING: 'SET_FORM_SETTING',
  LOAD_FORM: 'LOAD_FORM',
  SAVE_FORM_START: 'SAVE_FORM_START',
  SAVE_FORM_SUCCESS: 'SAVE_FORM_SUCCESS',
  SAVE_FORM_ERROR: 'SAVE_FORM_ERROR',
  
  // Section actions
  ADD_SECTION: 'ADD_SECTION',
  DELETE_SECTION: 'DELETE_SECTION',
  DUPLICATE_SECTION: 'DUPLICATE_SECTION',
  MOVE_SECTION: 'MOVE_SECTION',
  REORDER_SECTIONS: 'REORDER_SECTIONS',
  UPDATE_SECTION_FIELD: 'UPDATE_SECTION_FIELD',
  SET_SECTION_DEPENDENCY: 'SET_SECTION_DEPENDENCY',
  SET_SECTION_TAG_EXPRESSION: 'SET_SECTION_TAG_EXPRESSION',
  TOGGLE_SECTION_EXPANDED: 'TOGGLE_SECTION_EXPANDED',
  
  // Question actions
  ADD_QUESTION: 'ADD_QUESTION',
  ADD_LINKED_QUESTION: 'ADD_LINKED_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
  DUPLICATE_QUESTION: 'DUPLICATE_QUESTION',
  MOVE_QUESTION: 'MOVE_QUESTION',
  MOVE_QUESTION_TO_SECTION: 'MOVE_QUESTION_TO_SECTION',
  REORDER_QUESTIONS: 'REORDER_QUESTIONS',
  UPDATE_QUESTION_FIELD: 'UPDATE_QUESTION_FIELD',
  SET_QUESTION_TYPE: 'SET_QUESTION_TYPE',
  SET_QUESTION_SETTINGS: 'SET_QUESTION_SETTINGS',
  SET_QUESTION_DEPENDENCY: 'SET_QUESTION_DEPENDENCY',
  SET_QUESTION_TAG_EXPRESSION: 'SET_QUESTION_TAG_EXPRESSION',
  
  // Option actions
  ADD_OPTION: 'ADD_OPTION',
  DELETE_OPTION: 'DELETE_OPTION',
  UPDATE_OPTION: 'UPDATE_OPTION',
  REORDER_OPTIONS: 'REORDER_OPTIONS',
  
  // UI actions
  SET_VALIDATION_ERRORS: 'SET_VALIDATION_ERRORS'
};
