"""empty message

Revision ID: 0023aeda53b0
Revises: d7f3adff2c9f
Create Date: 2020-02-12 15:59:55.882521

"""

# revision identifiers, used by Alembic.
revision = '0023aeda53b0'
down_revision = 'd7f3adff2c9f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_form', 'deadline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
