"""empty message

Revision ID: 04188674173e
Revises: 2717ef90a874
Create Date: 2020-02-29 12:41:36.494488

"""

# revision identifiers, used by Alembic.
revision = '04188674173e'
down_revision = '2717ef90a874'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('depends_on_question_id', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('show_for_values', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'question', 'question', ['depends_on_question_id'], ['id'])
    op.add_column('section', sa.Column('depends_on_question_id', sa.Integer(), nullable=True))
    op.add_column('section', sa.Column('show_for_values', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'section', 'question', ['depends_on_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.drop_column('section', 'show_for_values')
    op.drop_column('section', 'depends_on_question_id')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'show_for_values')
    op.drop_column('question', 'depends_on_question_id')
    # ### end Alembic commands ###
