"""Create Reviewer Tag table

Revision ID: 062dc67db351
Revises: 2ae07ae036c1
Create Date: 2024-04-01 12:50:47.507594

"""

# revision identifiers, used by Alembic.
revision = '062dc67db351'
down_revision = '2ae07ae036c1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewer_tag')
    # ### end Alembic commands ###
