"""empty message

Revision ID: 0669d92f45af
Revises: 85d13062a5e7
Create Date: 2020-02-29 08:58:07.300715

"""

# revision identifiers, used by Alembic.
revision = '0669d92f45af'
down_revision = '85d13062a5e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_form_id', sa.Integer(), nullable=False),
    sa.Column('num_reviews_required', sa.Integer(), nullable=True),
    sa.Column('num_optional_reviews', sa.Integer(), nullable=True),
    sa.Column('drop_optional_question_id', sa.Integer(), nullable=False),
    sa.Column('drop_optional_agreement_values', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['drop_optional_question_id'], ['review_question.id'], ),
    sa.ForeignKeyConstraint(['review_form_id'], ['review_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_configuration')
    # ### end Alembic commands ###
