"""Add stages to review form.

Revision ID: 07d536b58953
Revises: 2dfc0d119bc2
Create Date: 2021-04-05 12:26:15.324811

"""

# revision identifiers, used by Alembic.
revision = '07d536b58953'
down_revision = '2dfc0d119bc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_form', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('review_form', sa.Column('stage', sa.Integer(), nullable=True))

    op.execute("""UPDATE review_form SET stage = 1, active = True;""")

    op.alter_column('review_form', 'active', nullable=False)
    op.alter_column('review_form', 'stage', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_form', 'stage')
    op.drop_column('review_form', 'active')
    # ### end Alembic commands ###
