"""Add submission and revision id for response and answer

Revision ID: 094f072eb68b
Revises: 6a073dd1e30d
Create Date: 2023-03-26 20:53:06.593375

"""

# revision identifiers, used by Alembic.
revision = '094f072eb68b'
down_revision = '6a073dd1e30d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.add_column('response', sa.Column('version_id', sa.Integer(), nullable=True))
    
    op.create_unique_constraint('responses_key', 'response', ['id', 'submission_id', 'version_id'])
    op.execute("""UPDATE response SET submission_id = 1, version_id = 1;""")
    
    op.alter_column('response', sa.Column('submission_id', sa.Integer(), nullable=False))
    op.alter_column('response', sa.Column('version_id', sa.Integer(), nullable=False))
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'version_id')
    op.drop_column('response', 'submission_id')
    # ### end Alembic commands ###
