"""empty message

Revision ID: 095650171b26
Revises: 349da0b8780a
Create Date: 2023-03-26 08:16:16.830657

"""

# revision identifiers, used by Alembic.
revision = '095650171b26'
down_revision = '349da0b8780a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

tag_type = postgresql.ENUM('REGISTERED', name='tag_type')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tag_type.create(op.get_bind())
    op.add_column('tag', sa.Column('type', sa.Enum('REGISTERED', name='tag_type'), nullable=True))
    op.add_column('tag_translation', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_translation', 'description')
    op.drop_column('tag', 'type')
    tag_type.drop(op.get_bind())
    # ### end Alembic commands ###