"""empty message

Revision ID: 09ade4d4fe13
Revises: 7f3d601390cb
Create Date: 2019-01-22 08:44:07.412831

"""

# revision identifiers, used by Alembic.
revision = '09ade4d4fe13'
down_revision = '7f3d601390cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('user_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'app_user', 'user_category', ['user_category_id'], ['user_category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_column('app_user', 'user_category_id')
    # ### end Alembic commands ###
