"""empty message

Revision ID: 09b2cc2105be
Revises: a5876b93baee
Create Date: 2019-05-29 09:23:37.584627

"""

# revision identifiers, used by Alembic.
revision = "09b2cc2105be"
down_revision = "a5876b93baee"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("offer_date", sa.DateTime(), nullable=False),
        sa.Column("expiry_date", sa.DateTime(), nullable=False),
        sa.Column("payement_required", sa.String(50), nullable=False),
        sa.Column("travel_award", sa.String(50), nullable=False),
        sa.Column("accomodation_award", sa.String(50), nullable=False),
        sa.Column("accepted", sa.String(50), nullable=False),
        sa.Column("rejected", sa.String(50), nullable=False),
        sa.Column("rejected_reason", sa.String(50), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offer")
    # ### end Alembic commands ###
