import sqlalchemy as sa
from alembic import op
"""empty message

Revision ID: 0ab2d6bca67d
Revises: efc34996e565
Create Date: 2019-03-14 11:31:38.967544

"""

# revision identifiers, used by Alembic.
revision = '0ab2d6bca67d'
down_revision = 'efc34996e565'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column(
        'user_dateOfBirth', sa.DateTime(), nullable=True))
    op.add_column('app_user', sa.Column('user_primaryLanguage',
                                        sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'user_primaryLanguage')
    op.drop_column('app_user', 'user_dateOfBirth')
    # ### end Alembic commands ###
