"""empty message

Revision ID: 0d063877a565
Revises: b19ea01cd78f
Create Date: 2022-06-20 13:52:06.345756

"""

# revision identifiers, used by Alembic.
revision = '0d063877a565'
down_revision = 'b19ea01cd78f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('iso_currency_code', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'iso_currency_code')
    # ### end Alembic commands ###
