"""empty message

Revision ID: 0e13fd6f0d2a
Revises: 016571f41a20
Create Date: 2020-01-24 17:15:03.763886

"""

# revision identifiers, used by Alembic.
revision = "0e13fd6f0d2a"
down_revision = "016571f41a20"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("template", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "event_id", name="uq_email_template_key_event_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_template")
    # ### end Alembic commands ###
