"""empty message

Revision ID: 10fa76d53339
Revises: 245d12695c69
Create Date: 2020-03-12 17:01:07.966940

"""

# revision identifiers, used by Alembic.
revision = '10fa76d53339'
down_revision = '245d12695c69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'nomination_email')
    op.drop_column('response', 'nomination_firstname')
    op.drop_column('response', 'nomination_title')
    op.drop_column('response', 'nomination_lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('nomination_lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_title', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_firstname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
