"""empty message

Revision ID: 122dd6a5c035
Revises: 09b2cc2105be
Create Date: 2019-05-29 10:54:54.766117

"""

# revision identifiers, used by Alembic.
revision = '122dd6a5c035'
down_revision = '09b2cc2105be'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'accepted', nullable=True)
    op.alter_column('offer', 'rejected', nullable=True)
    op.alter_column('offer', 'rejected_reason', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'accepted', nullable=False)
    op.alter_column('offer', 'rejected', nullable=False)
    op.alter_column('offer', 'rejected_reason', nullable=False)
    # ### end Alembic commands ###
