"""empty message

Revision ID: 13cec30f2a22
Revises: f9e34f59d257
Create Date: 2022-06-27 17:49:43.666320

"""

# revision identifiers, used by Alembic.
revision = '13cec30f2a22'
down_revision = 'f9e34f59d257'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('customer_name', sa.String(length=200), nullable=False))
    op.add_column('invoice', sa.Column('due_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'due_date')
    op.drop_column('invoice', 'customer_name')
    # ### end Alembic commands ###
