"""empty message

Revision ID: 186e11949103
Revises: 07d536b58953
Create Date: 2021-05-13 21:49:50.765632

"""

# revision identifiers, used by Alembic.
revision = '186e11949103'
down_revision = '07d536b58953'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
