"""empty message

Revision ID: 1993beca93d7
Revises: 3e7bdff8af80
Create Date: 2020-02-06 13:43:00.272015

"""

# revision identifiers, used by Alembic.
revision = '1993beca93d7'
down_revision = '3e7bdff8af80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_request_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_document', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reference_request_id'], ['reference_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference')
    # ### end Alembic commands ###
