"""Add invited guest and offer tags.

Revision ID: 1cdf3a2cf02b
Revises: 095650171b26
Create Date: 2023-03-27 23:20:56.293073

"""

# revision identifiers, used by Alembic.
revision = '1cdf3a2cf02b'
down_revision = '095650171b26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invited_guest_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invited_guest_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invited_guest_id'], ['invited_guest.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_tag')
    op.drop_table('invited_guest_tag')
    # ### end Alembic commands ###
