"""empty message

Revision ID: 20bb90b8010c
Revises: b4c1dfa70233
Create Date: 2019-03-23 18:29:20.289469

"""

# revision identifiers, used by Alembic.
revision = '20bb90b8010c'
down_revision = 'b4c1dfa70233'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_form_id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_reviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_form_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('submitted_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.ForeignKeyConstraint(['review_form_id'], ['review_form.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_form_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('placeholder', sa.String(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('validation_regex', sa.String(), nullable=True),
    sa.Column('validation_text', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['review_form_id'], ['review_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_response_id', sa.Integer(), nullable=False),
    sa.Column('review_question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['review_question_id'], ['review_question.id'], ),
    sa.ForeignKeyConstraint(['review_response_id'], ['review_response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_score')
    op.drop_table('review_question')
    op.drop_table('review_response')
    op.drop_table('response_reviewer')
    op.drop_table('review_form')
    # ### end Alembic commands ###
