"""Change offer payment_amount to event_fee_id

Revision ID: 21018201594d
Revises: 70b2a4f4a596
Create Date: 2024-05-19 18:01:07.213397

"""

# revision identifiers, used by Alembic.
revision = '21018201594d'
down_revision = '70b2a4f4a596'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('event_fee_id', sa.Integer(), nullable=True))
    op.create_foreign_key('offer_event_fee', 'offer', 'event_fee', ['event_fee_id'], ['id'])
    op.drop_column('offer', 'payment_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('payment_amount', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('offer_event_fee', 'offer', type_='foreignkey')
    op.drop_column('offer', 'event_fee_id')
    # ### end Alembic commands ###
