"""Creating indexes on tables

Revision ID: 226f2824d6f6
Revises: c56a126e3ee4
Create Date: 2020-02-06 17:44:06.222968

"""

# revision identifiers, used by Alembic.
revision = '226f2824d6f6'
down_revision = 'c56a126e3ee4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_answer_question_id'), 'answer', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_response_id'), 'answer', ['response_id'], unique=False)
    op.create_index(op.f('ix_password_reset_user_id'), 'password_reset', ['user_id'], unique=False)
    op.create_index(op.f('ix_response_application_form_id'), 'response', ['application_form_id'], unique=False)
    op.create_index(op.f('ix_response_user_id'), 'response', ['user_id'], unique=False)
    op.create_index(op.f('ix_response_reviewer_response_id'), 'response_reviewer', ['response_id'], unique=False)
    op.create_index(op.f('ix_response_reviewer_reviewer_user_id'), 'response_reviewer', ['reviewer_user_id'], unique=False)
    op.create_index(op.f('ix_user_comment_event_id'), 'user_comment', ['event_id'], unique=False)
    op.create_index(op.f('ix_user_comment_user_id'), 'user_comment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_comment_user_id'), table_name='user_comment')
    op.drop_index(op.f('ix_user_comment_event_id'), table_name='user_comment')
    op.drop_index(op.f('ix_response_reviewer_reviewer_user_id'), table_name='response_reviewer')
    op.drop_index(op.f('ix_response_reviewer_response_id'), table_name='response_reviewer')
    op.drop_index(op.f('ix_response_user_id'), table_name='response')
    op.drop_index(op.f('ix_response_application_form_id'), table_name='response')
    op.drop_index(op.f('ix_password_reset_user_id'), table_name='password_reset')
    op.drop_index(op.f('ix_answer_response_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_question_id'), table_name='answer')
    # ### end Alembic commands ###
