"""empty message

Revision ID: 26cac078611a
Revises: 3e7bdff8af80
Create Date: 2020-02-11 11:36:27.442626

"""

# revision identifiers, used by Alembic.
revision = '26cac078611a'
down_revision = '3e7bdff8af80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('nominations', sa.Boolean(), nullable=True))
    op.execute("UPDATE application_form SET nominations = false")
    op.alter_column('application_form', 'nominations', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_form', 'nominations')
    # ### end Alembic commands ###
