"""Add response index

Revision ID: 2961527fe515
Revises: 49663ad38428
Create Date: 2025-03-23 09:47:31.810696

"""

# revision identifiers, used by Alembic.
revision = '2961527fe515'
down_revision = '49663ad38428'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('response_application_form_lookup', 'response', ['application_form_id'], unique=False, postgresql_where=sa.text('is_submitted IS true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('response_application_form_lookup', table_name='response', postgresql_where=sa.text('is_submitted IS true'))
    # ### end Alembic commands ###
