"""migrations for add_journal_event_type

Revision ID: 2ae07ae036c1
Revises: ef75fde5102c
Create Date: 2024-03-13 07:22:44.928325

"""

# revision identifiers, used by Alembic.
revision = '2ae07ae036c1'
down_revision = 'ef75fde5102c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('event', 'event_type',
               existing_type=postgresql.ENUM('AWARD', 'EVENT', 'CALL', 'PROGRAMME', 'JOURNAL', 'CONTINUOUS_JOURNAL', name='event_type'),
               type_=sa.Enum('EVENT', 'AWARD', 'CALL', 'PROGRAMME', 'JOURNAL', name='event_type'),
               existing_nullable=False)

    op.alter_column('tag', 'tag_type',
               existing_type=postgresql.ENUM('RESPONSE', 'REGISTRATION', 'GRANT', 'QUESTION', name='tag_type'),
               type_=sa.Enum('RESPONSE', 'REGISTRATION', 'GRANT', 'QUESTION', name='tag_type'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'tag_type',
               existing_type=sa.Enum('RESPONSE', 'REGISTRATION', 'GRANT', 'QUESTION', name='tag_type'),
               type_=postgresql.ENUM('RESPONSE', 'REGISTRATION', 'GRANT', 'QUESTION', name='tag_type'),
               existing_nullable=True)
    
    op.alter_column('event', 'event_type',
               existing_type=sa.Enum('EVENT', 'AWARD', 'CALL', 'PROGRAMME', 'JOURNAL', name='event_type'),
               type_=postgresql.ENUM('AWARD', 'EVENT', 'CALL', 'PROGRAMME', 'JOURNAL', 'CONTINUOUS_JOURNAL', name='event_type'),
               existing_nullable=False)
    
    # ### end Alembic commands ###
