"""empty message

Revision ID: 2b5e02979cbb
Revises: 76c9226545bb
Create Date: 2021-01-26 22:33:24.231261

"""

# revision identifiers, used by Alembic.
revision = '2b5e02979cbb'
down_revision = '76c9226545bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
