"""empty message

Revision ID: 2d7f5a0819e3
Revises: ef75fde5102c
Create Date: 2024-03-08 07:08:08.727670

"""

# revision identifiers, used by Alembic.
revision = '2d7f5a0819e3'
down_revision = 'ef75fde5102c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('answer_question_lookup', table_name='answer')
    op.drop_index('answer_response_lookup', table_name='answer')
    op.alter_column('event', 'event_type',
               existing_type=postgresql.ENUM('AWARD', 'EVENT', 'CALL', 'PROGRAMME', 'JOURNAL', name='event_type'),
               type_=sa.Enum('EVENT', 'AWARD', 'CALL', 'PROGRAMME', 'JOURNAL', name='event_type'),
               existing_nullable=False)
    op.drop_index('guest_registration_answer_lookup', table_name='guest_registration_answer')
    op.drop_index('invited_guest_event_lookup', table_name='invited_guest')
    op.drop_index('invited_guest_lookup', table_name='invited_guest')
    op.drop_index('registration_answer_lookup', table_name='registration_answer')
    op.alter_column('tag', 'tag_type',
               existing_type=postgresql.ENUM('RESPONSE', 'REGISTRATION', 'GRANT', 'QUESTION', name='tag_type'),
               type_=sa.Enum('RESPONSE', 'REGISTRATION', 'GRANT', 'QUESTION', name='tag_type'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'tag_type',
               existing_type=sa.Enum('RESPONSE', 'REGISTRATION', 'GRANT', 'QUESTION', name='tag_type'),
               type_=postgresql.ENUM('RESPONSE', 'REGISTRATION', 'GRANT', 'QUESTION', name='tag_type'),
               existing_nullable=True)
    op.create_index('registration_answer_lookup', 'registration_answer', ['registration_id', 'registration_question_id'], unique=False)
    op.create_index('invited_guest_lookup', 'invited_guest', ['event_id', 'user_id'], unique=False)
    op.create_index('invited_guest_event_lookup', 'invited_guest', ['event_id'], unique=False)
    op.create_index('guest_registration_answer_lookup', 'guest_registration_answer', ['guest_registration_id', 'registration_question_id', 'is_active'], unique=False)
    op.alter_column('event', 'event_type',
               existing_type=sa.Enum('EVENT', 'AWARD', 'CALL', 'PROGRAMME', 'JOURNAL', name='event_type'),
               type_=postgresql.ENUM('AWARD', 'EVENT', 'CALL', 'PROGRAMME', 'JOURNAL', name='event_type'),
               existing_nullable=False)
    op.create_index('answer_response_lookup', 'answer', ['response_id', 'is_active'], unique=False)
    op.create_index('answer_question_lookup', 'answer', ['question_id', 'response_id', 'is_active'], unique=False)
    # ### end Alembic commands ###
