"""Add Review Sections

Revision ID: 2dfc0d119bc2
Revises: 76c9226545bb
Create Date: 2021-03-08 22:05:53.267047

"""

# revision identifiers, used by Alembic.
revision = "2dfc0d119bc2"
down_revision = "76c9226545bb"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_section",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_form_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_form_id"],
            ["review_form.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review_section_translation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_section_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("headline", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_section_id"],
            ["review_section.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "review_section_id", "language", name="uq_review_section_id_language"
        ),
    )

    op.add_column(
        "review_question", sa.Column("review_section_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "review_question_review_form_id_fkey", "review_question", type_="foreignkey"
    )

    # Create dummy section for all existing review forms, link existing questions to this new section
    op.execute(
        """
    INSERT INTO review_section(review_form_id, "order") SELECT id, 1 FROM review_form;
    """
    )

    op.execute(
        """
    INSERT INTO review_section_translation(review_section_id, language, headline, description)
    SELECT id, 'en', NULL, NULL FROM review_section;
    """
    )

    op.execute(
        """
    UPDATE review_question SET review_section_id = review_section.id
    FROM review_section
    WHERE review_section.review_form_id = review_question.review_form_id;
    """
    )

    op.alter_column("review_question", "review_section_id", nullable=False)
    op.create_foreign_key(
        "review_question_review_section_id_fkey",
        "review_question",
        "review_section",
        ["review_section_id"],
        ["id"],
    )
    op.drop_column("review_question", "review_form_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_question",
        sa.Column("review_form_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # op.drop_constraint('review_question_review_section_id_fkey', 'review_question', type_='foreignkey')

    # Link review questions back to review_forms
    op.execute(
        """
    UPDATE review_question SET review_form_id = review_section.review_form_id
    FROM review_section
    WHERE review_section.id = review_question.review_section_id;
    """
    )

    op.alter_column("review_question", "review_form_id", nullable=False)
    op.create_foreign_key(
        "review_question_review_form_id_fkey",
        "review_question",
        "review_form",
        ["review_form_id"],
        ["id"],
    )
    op.drop_column("review_question", "review_section_id")
    op.drop_table("review_section_translation")
    op.drop_table("review_section")
    # ### end Alembic commands ###
