"""Add language to review response

Revision ID: 33b563f7be6b
Revises: 3454400e3738
Create Date: 2020-10-24 21:09:28.069615

"""

# revision identifiers, used by Alembic.
revision = '33b563f7be6b'
down_revision = '3454400e3738'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_response', sa.Column('language', sa.String(length=2), nullable=True))
    op.execute("UPDATE review_response SET language = 'en'")
    op.alter_column('review_response', 'language', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_response', 'language')
    # ### end Alembic commands ###
