"""empty message

Revision ID: 33e175de61ca
Revises: b7006cbdd923
Create Date: 2020-01-30 16:54:57.794843

"""

# revision identifiers, used by Alembic.
revision = "33e175de61ca"
down_revision = "b7006cbdd923"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_template", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_template", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
