"""Add Review Question Translation Table

Revision ID: 3454400e3738
Revises: 039addb92a03
Create Date: 2020-10-21 21:10:01.550893

"""

# revision identifiers, used by Alembic.
revision = "3454400e3738"
down_revision = "039addb92a03"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_question_translation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_question_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("headline", sa.String(), nullable=True),
        sa.Column("placeholder", sa.String(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("validation_regex", sa.String(), nullable=True),
        sa.Column("validation_text", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_question_id"],
            ["review_question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "review_question_id", "language", name="uq_review_question_id_language"
        ),
    )

    # Copy data from review_question to review_question_translation
    op.execute(
        """
        INSERT INTO review_question_translation(
            review_question_id, 
            language, 
            description, 
            headline, 
            placeholder, 
            options, 
            validation_regex, 
            validation_text)
        SELECT 
            id, 
            'en', 
            description, 
            headline, 
            placeholder, 
            options, 
            validation_regex, 
            validation_text
        FROM review_question
    """
    )

    op.drop_column("review_question", "description")
    op.drop_column("review_question", "headline")
    op.drop_column("review_question", "validation_text")
    op.drop_column("review_question", "validation_regex")
    op.drop_column("review_question", "placeholder")
    op.drop_column("review_question", "options")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_question",
        sa.Column(
            "options",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "review_question",
        sa.Column("placeholder", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "review_question",
        sa.Column("validation_regex", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "review_question",
        sa.Column("validation_text", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "review_question",
        sa.Column("headline", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "review_question",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )

    op.execute(
        """
    UPDATE review_question SET
        options = (SELECT options from review_question_translation WHERE review_question.id = review_question_translation.review_question_id AND review_question_translation.language = 'en'),
        placeholder = (SELECT placeholder from review_question_translation WHERE review_question.id = review_question_translation.review_question_id AND review_question_translation.language = 'en'),
        validation_regex = (SELECT validation_regex from review_question_translation WHERE review_question.id = review_question_translation.review_question_id AND review_question_translation.language = 'en'),
        validation_text = (SELECT validation_text from review_question_translation WHERE review_question.id = review_question_translation.review_question_id AND review_question_translation.language = 'en'),
        headline = (SELECT headline from review_question_translation WHERE review_question.id = review_question_translation.review_question_id AND review_question_translation.language = 'en'),
        description = (SELECT description from review_question_translation WHERE review_question.id = review_question_translation.review_question_id AND review_question_translation.language = 'en')
    """
    )

    op.drop_table("review_question_translation")
    # ### end Alembic commands ###
