"""empty message

Revision ID: 351c26992f23
Revises: None
Create Date: 2014-09-19 10:47:39.386944

"""

# revision identifiers, used by Alembic.
revision = '351c26992f23'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    ### end Alembic commands ###

    op.create_unique_constraint('unique_user_code', 'password_reset', ['user_id', 'code'])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset')
    op.drop_table('app_user')
    ### end Alembic commands ###
