"""empty message

Revision ID: 358d0e0282bb
Revises: 3dcef2e3c442
Create Date: 2019-04-22 12:34:18.443323

"""

# revision identifiers, used by Alembic.
revision = "358d0e0282bb"
down_revision = "3dcef2e3c442"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment_by_user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_by_user_id"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_comment")
    # ### end Alembic commands ###
