"""empty message

Revision ID: 36235e184d09
Revises: 3ec3ed0eb3c6
Create Date: 2020-04-02 17:46:20.544278

"""

# revision identifiers, used by Alembic.
revision = '36235e184d09'
down_revision = '3ec3ed0eb3c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'nomination_email')
    op.drop_column('response', 'nomination_firstname')
    op.drop_column('response', 'nomination_title')
    op.drop_column('response', 'nomination_lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('nomination_lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_title', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_firstname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
