"""empty message

Revision ID: 37fbee2da7b7
Revises: 72548fc390d4
Create Date: 2020-02-16 19:52:59.832580

"""

# revision identifiers, used by Alembic.
revision = '37fbee2da7b7'
down_revision = '72548fc390d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


event_type = postgresql.ENUM('AWARD', 'EVENT', name='event_type')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    event_type.create(op.get_bind())
    op.add_column('event', sa.Column('event_type', sa.Enum('AWARD', 'EVENT', name='event_type'), nullable=True))
    op.execute("UPDATE event SET event_type = 'EVENT'")
    op.alter_column('event', 'event_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_type')
    event_type.drop(op.get_bind())
    # ### end Alembic commands ###
