"""empty message

Revision ID: 3dcef2e3c442
Revises: 1349a2c924f4
Create Date: 2019-03-29 07:23:12.851270

"""

# revision identifiers, used by Alembic.
revision = '3dcef2e3c442'
down_revision = '1349a2c924f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'section_name_key', 'section', type_='unique')
    op.drop_constraint(u'uq_section_order', 'section', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'uq_section_order', 'section', ['order'])
    op.create_unique_constraint(u'section_name_key', 'section', ['name'])
    # ### end Alembic commands ###
