"""Remove award columns from offer

Revision ID: 3e271c360a92
Revises: e0a0dd8b8177
Create Date: 2023-05-02 00:47:54.637897

"""

# revision identifiers, used by Alembic.
revision = '3e271c360a92'
down_revision = 'e0a0dd8b8177'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'accommodation_award')
    op.drop_column('offer', 'travel_award')
    op.drop_column('offer', 'accepted_accommodation_award')
    op.drop_column('offer', 'accepted_travel_award')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('accepted_travel_award', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('accepted_accommodation_award', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('travel_award', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('accommodation_award', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
