"""empty message

Revision ID: 44df297ad858
Revises: 910e74b87f06
Create Date: 2020-07-28 18:20:51.645642

"""

# revision identifiers, used by Alembic.
revision = '44df297ad858'
down_revision = '910e74b87f06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'name')
    op.drop_column('event', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.execute("""
    UPDATE event
        SET 
	        name = (SELECT name FROM event_translation WHERE event.id = event_translation.event_id AND event_translation.language = 'en'),
	        description = (SELECT description FROM event_translation WHERE event.id = event_translation.event_id AND event_translation.language = 'en')
    """)

    op.alter_column('event', 'name', nullable=False)
    op.alter_column('event', 'description', nullable=False)
    # ### end Alembic commands ###
