"""Add event contact and image.

Revision ID: 496db296e680
Revises: 0d954e0cafa3
Create Date: 2026-06-06 14:10:29.778757

"""

# revision identifiers, used by Alembic.
revision = '496db296e680'
down_revision = '0d954e0cafa3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('event', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'image')
    op.drop_column('event', 'contact_email')
    # ### end Alembic commands ###
