"""Link user to organisation

Revision ID: 4d8b254d7e7e
Revises: 016571f41a20
Create Date: 2020-01-22 17:42:42.968199

"""

# revision identifiers, used by Alembic.
revision = '4d8b254d7e7e'
down_revision = '016571f41a20'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import orm
from app import db
from app.users.models import AppUser

Base = declarative_base()

class Organisation(db.Model):
    
    __tablename__ = "organisation"
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    system_name = db.Column(db.String(50), nullable=False)
    small_logo = db.Column(db.String(100), nullable=False)
    large_logo = db.Column(db.String(100), nullable=False)
    domain = db.Column(db.String(100), nullable=False)

    def __init__(self, name, system_name, small_logo, large_logo, domain):
        self.name = name
        self.small_logo = small_logo
        self.large_logo = large_logo
        self.domain = domain
        self.system_name = system_name


def upgrade():
    Base.metadata.bind = op.get_bind()
    session = orm.Session(bind=Base.metadata.bind)

    op.add_column('app_user', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_organisation', 'app_user', 'organisation', ['organisation_id'], ['id'])

    # Populate with organisation 1 and make non-nullable
    users = session.query(AppUser).all()
    for user in users:
        user.organisation_id = 1
    session.commit()
    
    op.alter_column('app_user', 'organisation_id', nullable=False)

    op.add_column('organisation', sa.Column('system_name', sa.String(length=50), nullable=True))

    indaba = session.query(Organisation).filter_by(id=1).first()
    if indaba:
        indaba.system_name = 'Baobab'
    
    eeml = session.query(Organisation).filter_by(id=2).first()
    if eeml:
        eeml.system_name = 'EEML Application Portal'

    local = session.query(Organisation).filter_by(id=3).first()
    if local:
        local.system_name = 'Baobab Dev'

    session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'system_name')
    op.drop_constraint('fk_user_organisation', 'app_user', type_='foreignkey')
    op.drop_column('app_user', 'organisation_id')
    # ### end Alembic commands ###
