"""Link user to organisation

Revision ID: 4d8b254d7e7e
Revises: 016571f41a20
Create Date: 2020-01-22 17:42:42.968199

"""

# revision identifiers, used by Alembic.
revision = '4d8b254d7e7e'
down_revision = '016571f41a20'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import orm
from app import db

Base = declarative_base()


def upgrade():
    Base.metadata.bind = op.get_bind()
    session = orm.Session(bind=Base.metadata.bind)

    op.add_column('app_user', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_organisation', 'app_user', 'organisation', ['organisation_id'], ['id'])

    op.execute("""UPDATE app_users SET organisation_id = 1""")
    op.alter_column('app_user', 'organisation_id', nullable=False)

    op.add_column('organisation', sa.Column('system_name', sa.String(length=50), nullable=True))

    op.execute("""UPDATE organisation SET system_name = 'Baobab' WHERE id = 1""")
    op.execute("""UPDATE organisation SET system_name = 'EEML Portal' WHERE id = 2""")
    op.execute("""UPDATE organisation SET system_name = 'Baobab Dev' WHERE id = 3""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'system_name')
    op.drop_constraint('fk_user_organisation', 'app_user', type_='foreignkey')
    op.drop_column('app_user', 'organisation_id')
    # ### end Alembic commands ###
