"""empty message

Revision ID: 4de2ac6e4715
Revises: c5a76ae67dd0
Create Date: 2022-06-06 15:51:10.781081

"""

# revision identifiers, used by Alembic.
revision = '4de2ac6e4715'
down_revision = 'c5a76ae67dd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=50), nullable=False),
    sa.Column('payment_intent', sa.String(length=50), nullable=False),
    sa.Column('event', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_stripe_webhook_events_idempotency_key')
    )
    op.create_table('invoice_payment_intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_intent', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_intent', name='uq_invoice_payment_intent_payment_intent')
    )
    op.add_column('invoice_payment_status', sa.Column('created_at_unix', sa.Integer(), nullable=False))
    op.alter_column('invoice_payment_status', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_payment_status', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoice_payment_status', 'created_at_unix')
    op.drop_table('invoice_payment_intent')
    op.drop_table('stripe_webhook_event')
    # ### end Alembic commands ###
