"""empty message


Revision ID: 539d0567cd6c
Revises: c0885e531d29
Create Date: 2019-06-10 09:19:00.373662

"""

# revision identifiers, used by Alembic.
revision = '539d0567cd6c'
down_revision = 'c0885e531d29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'accepted')
    # ### end Alembic commands ###
