"""empty message

Revision ID: 54aba10497f4
Revises: d7f3adff2c9f
Create Date: 2020-02-14 20:24:03.644194

"""

# revision identifiers, used by Alembic.
revision = '54aba10497f4'
down_revision = 'd7f3adff2c9f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=20), nullable=False),
    sa.Column('guid', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('guid')
    )
    op.drop_column(u'application_form', 'deadline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'application_form', sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_table('file')
    # ### end Alembic commands ###
