"""
Revision ID: 5d5b0524b4fa
Revises: 627a96dad7e8
Create Date: 2023-05-27 07:46:16.735763

"""

# revision identifiers, used by Alembic.
revision = '5d5b0524b4fa'
down_revision = '627a96dad7e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_response_parent_id', 'response', 'response', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response', type_='foreignkey')
    op.drop_column('response', 'parent_id')
    # ### end Alembic commands ###
