"""empty message

Revision ID: 62352569fb5d
Revises: 04188674173e
Create Date: 2020-02-29 15:23:55.429403

"""

# revision identifiers, used by Alembic.
revision = "62352569fb5d"
down_revision = "04188674173e"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
