"""Update registration section to use tag instead of travel/accommodation/payment flags.

Revision ID: 627a96dad7e8
Revises: d54c936be94d
Create Date: 2023-05-06 20:10:26.148329

"""

# revision identifiers, used by Alembic.
revision = '627a96dad7e8'
down_revision = 'd54c936be94d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_section', sa.Column('show_for_tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registration_section', 'tag', ['show_for_tag_id'], ['id'])
    op.drop_column('registration_section', 'show_for_travel_award')
    op.drop_column('registration_section', 'show_for_accommodation_award')
    op.drop_column('registration_section', 'show_for_payment_required')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_section', sa.Column('show_for_payment_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('registration_section', sa.Column('show_for_accommodation_award', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('registration_section', sa.Column('show_for_travel_award', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'registration_section', type_='foreignkey')
    op.drop_column('registration_section', 'show_for_tag_id')
    # ### end Alembic commands ###
