"""Models for generic forms.

Revision ID: 661475bafb4d
Revises: 7fb62ea19309
Create Date: 2025-12-24 11:55:46.454483

"""

# revision identifiers, used by Alembic.
revision = '661475bafb4d'
down_revision = '7fb62ea19309'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('multiple_responses', sa.Boolean(), nullable=False),
    sa.Column('linked_form_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['linked_form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_withdrawn', sa.Boolean(), nullable=False),
    sa.Column('withdrawn_timestamp', sa.DateTime(), nullable=True),
    sa.Column('started_timestamp', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('parent_response_id', sa.Integer(), nullable=True),
    sa.Column('linked_response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['linked_response_id'], ['form_response.id'], ),
    sa.ForeignKeyConstraint(['parent_response_id'], ['form_response.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_form_response_lookup', 'form_response', ['form_id', 'user_id'], unique=False)
    op.create_index('idx_submitted_responses', 'form_response', ['form_id', 'is_submitted'], unique=False)
    op.create_table('form_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dependency_expression', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dependency_expression', sa.JSON(), nullable=True),
    sa.Column('linked_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['linked_question_id'], ['form_question.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['form_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_section_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_section_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['form_section_id'], ['form_section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_section_id', 'language')
    )
    op.create_table('form_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['form_question.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['form_response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_answer_lookup', 'form_answer', ['question_id', 'response_id', 'is_active'], unique=False)
    op.create_index('idx_response_answers', 'form_answer', ['response_id', 'is_active'], unique=False)
    op.create_table('form_question_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_question_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('validation_regex', sa.String(length=500), nullable=True),
    sa.Column('validation_text', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['form_question_id'], ['form_question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_question_id', 'language')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_question_translation')
    op.drop_index('idx_response_answers', table_name='form_answer')
    op.drop_index('idx_answer_lookup', table_name='form_answer')
    op.drop_table('form_answer')
    op.drop_table('form_section_translation')
    op.drop_table('form_question')
    op.drop_table('form_section')
    op.drop_index('idx_submitted_responses', table_name='form_response')
    op.drop_index('idx_form_response_lookup', table_name='form_response')
    op.drop_table('form_response')
    op.drop_table('form')
    # ### end Alembic commands ###
