"""empty message

Revision ID: 67ee859efeef
Revises: e622c3deea5d
Create Date: 2020-02-06 06:40:59.842097

"""

# revision identifiers, used by Alembic.
revision = '67ee859efeef'
down_revision = 'e622c3deea5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_request_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_document', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reference_request_id'], ['reference_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference')
    # ### end Alembic commands ###
