"""Removes dates for Continuous Journal Events

Revision ID: 6a073dd1e30d
Revises: 349da0b8780a
Create Date: 2023-02-23 09:51:13.409030

"""

# revision identifiers, used by Alembic.
revision = '6a073dd1e30d'
down_revision = '349da0b8780a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'application_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'application_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'review_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'review_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'selection_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'selection_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'offer_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'offer_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'registration_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'registration_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'registration_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'registration_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'offer_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'offer_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'selection_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'selection_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'review_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'review_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'application_close',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event', 'application_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
