"""Add URL to organisation

Revision ID: 6d27df178e8e
Revises: 32c1ae6dd23a
Create Date: 2020-01-25 11:25:20.421281

"""

# revision identifiers, used by Alembic.
revision = '6d27df178e8e'
down_revision = '32c1ae6dd23a'

from alembic import op
import sqlalchemy as sa
from app.organisation.models import Organisation
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import orm
from app import db

Base = declarative_base()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('org_email_unique', 'app_user', ['email', 'organisation_id'])
    op.drop_constraint(u'app_user_email_key', 'app_user', type_='unique')
    op.add_column('organisation', sa.Column('url', sa.String(length=100), nullable=True))
    op.alter_column('organisation', 'system_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    Base.metadata.bind = op.get_bind()
    session = orm.Session(bind=Base.metadata.bind)

    indaba = session.query(Organisation).filter_by(id=1).first()
    if indaba:
        indaba.url = 'http://www.deeplearningindaba.com'
    
    eeml = session.query(Organisation).filter_by(id=2).first()
    if eeml:
        eeml.url = 'http://eeml.eu'

    local = session.query(Organisation).filter_by(id=3).first()
    if local:
        local.url = 'http://www.deeplearningindaba.com'

    session.commit()

    op.alter_column('organisation', 'url', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'system_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('organisation', 'url')
    op.create_unique_constraint(u'app_user_email_key', 'app_user', ['email'])
    op.drop_constraint('org_email_unique', 'app_user', type_='unique')
    # ### end Alembic commands ###
