"""Add PWA icons for Organisation.

Revision ID: 724757fece76
Revises: a3c7e1f2b9d4
Create Date: 2026-06-29 10:49:22.753238

"""

# revision identifiers, used by Alembic.
revision = '724757fece76'
down_revision = 'a3c7e1f2b9d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('pwa_icon_192', sa.String(length=255), nullable=True))
    op.add_column('organisation', sa.Column('pwa_icon_512', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'pwa_icon_512')
    op.drop_column('organisation', 'pwa_icon_192')
    # ### end Alembic commands ###
