"""empty message

Revision ID: 731321158cb0
Revises: 6a073dd1e30d
Create Date: 2023-03-31 11:42:59.535947

"""

# revision identifiers, used by Alembic.
revision = '731321158cb0'
down_revision = '6a073dd1e30d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_action_editor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('action_editor_user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['action_editor_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_action_editor')
    # ### end Alembic commands ###
