"""Add Action Editor to Reviewers

Revision ID: 731321158cb0
Revises: 6a073dd1e30d
Create Date: 2023-03-31 11:42:59.535947

"""

# revision identifiers, used by Alembic.
revision = '731321158cb0'
down_revision = '6a073dd1e30d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_reviewer', sa.Column('action_editor', sa.Boolean(), nullable=True))
    op.execute("""UPDATE response_reviewer SET action_editor=False""")
    op.alter_column('response_reviewer', 'action_editor', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_reviewer', 'action_editor')
    # ### end Alembic commands ###
