"""Add languages column to organisation

Revision ID: 742a2a556eb9
Revises: de12a6f382c1
Create Date: 2020-07-23 19:25:52.384921

"""

# revision identifiers, used by Alembic.
revision = '742a2a556eb9'
down_revision = 'de12a6f382c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('languages', sa.JSON(), nullable=True))
    op.execute("""UPDATE organisation SET languages = '[{"code": "en", "description": "English"}]'""")
    op.alter_column('organisation', 'languages', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'languages')
    # ### end Alembic commands ###
