"""empty message

Revision ID: 794506c08e10
Revises: 1afd8dfc8d05
Create Date: 2021-08-16 11:37:15.501414

"""

# revision identifiers, used by Alembic.
revision = "794506c08e10"
down_revision = "1afd8dfc8d05"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review_score", sa.Column("is_active", sa.Boolean, nullable=True))
    op.add_column(
        "guest_registration_answer", sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    op.add_column("answer", sa.Column("is_active", sa.Boolean(), nullable=True))

    op.add_column("review_score", sa.Column("created_on", sa.TIMESTAMP, nullable=True))
    op.add_column(
        "guest_registration_answer",
        sa.Column("created_on", sa.TIMESTAMP, nullable=True),
    )
    op.add_column("answer", sa.Column("created_on", sa.TIMESTAMP, nullable=True))

    op.execute("UPDATE review_score SET is_active = true, created_on=NOW()")
    op.execute(
        "UPDATE guest_registration_answer SET is_active = true, created_on=NOW()"
    )
    op.execute("UPDATE answer SET is_active = true, created_on=NOW()")

    op.alter_column("review_score", "is_active", nullable=False)
    op.alter_column("guest_registration_answer", "is_active", nullable=False)
    op.alter_column("answer", "is_active", nullable=False)

    op.alter_column("review_score", "created_on", nullable=False)
    op.alter_column("guest_registration_answer", "created_on", nullable=False)
    op.alter_column("answer", "created_on", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answer", "is_active")
    op.drop_column("guest_registration_answer", "is_active")
    op.drop_column("review_score", "is_active")

    op.drop_column("answer", "created_on")
    op.drop_column("guest_registration_answer", "created_on")
    op.drop_column("review_score", "created_on")
    # ### end Alembic commands ###
