"""empty message

Revision ID: 7e8bffa88454
Revises: c06c236ad4c5
Create Date: 2019-06-14 07:18:56.957803

"""

# revision identifiers, used by Alembic.
revision = '7e8bffa88454'
down_revision = 'c06c236ad4c5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
