"""empty message

Revision ID: 7f3d601390cb
Revises: 351c26992f23
Create Date: 2019-01-22 08:35:55.924317

"""

# revision identifiers, used by Alembic.
revision = '7f3d601390cb'
down_revision = '351c26992f23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('user_category',
    sa.Column('user_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_category_id')
    )
    op.create_table('user_disability',
    sa.Column('user_disability_id', sa.Integer(), nullable=False),
    sa.Column('disability_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_disability_id')
    )
    op.create_table('user_ethnicity',
    sa.Column('user_ethnicity_id', sa.Integer(), nullable=False),
    sa.Column('ethnicity_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_ethnicity_id')
    )
    op.create_table('user_gender',
    sa.Column('user_gender_id', sa.Integer(), nullable=False),
    sa.Column('gender_name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_gender_id')
    )
    op.create_table('user_title',
    sa.Column('user_title_id', sa.Integer(), nullable=False),
    sa.Column('title_name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_title_id')
    )
    op.add_column(u'app_user', sa.Column('affiliation', sa.String(length=255), nullable=True))
    op.add_column(u'app_user', sa.Column('deleted_datetime_utc', sa.DateTime(), nullable=True))
    op.add_column(u'app_user', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column(u'app_user', sa.Column('firstname', sa.String(length=100), nullable=True))
    op.add_column(u'app_user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column(u'app_user', sa.Column('lastname', sa.String(length=100), nullable=True))
    op.add_column(u'app_user', sa.Column('nationality_id', sa.Integer(), nullable=True))
    op.add_column(u'app_user', sa.Column('residence_id', sa.Integer(), nullable=True))
    op.add_column(u'app_user', sa.Column('user_disability_id', sa.Integer(), nullable=True))
    op.add_column(u'app_user', sa.Column('user_ethnicity_id', sa.Integer(), nullable=True))
    op.add_column(u'app_user', sa.Column('user_gender_id', sa.Integer(), nullable=True))
    op.add_column(u'app_user', sa.Column('user_title_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'app_user', 'user_gender', ['user_gender_id'], ['user_gender_id'])
    op.create_foreign_key(None, 'app_user', 'country', ['nationality_id'], ['country_id'])
    op.create_foreign_key(None, 'app_user', 'user_ethnicity', ['user_ethnicity_id'], ['user_ethnicity_id'])
    op.create_foreign_key(None, 'app_user', 'country', ['residence_id'], ['country_id'])
    op.create_foreign_key(None, 'app_user', 'user_disability', ['user_disability_id'], ['user_disability_id'])
    op.create_foreign_key(None, 'app_user', 'user_title', ['user_title_id'], ['user_title_id'])
    op.drop_index('unique_user_code', table_name='password_reset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_user_code', 'password_reset', ['user_id', 'code'], unique=True)
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_column(u'app_user', 'user_title_id')
    op.drop_column(u'app_user', 'user_gender_id')
    op.drop_column(u'app_user', 'user_ethnicity_id')
    op.drop_column(u'app_user', 'user_disability_id')
    op.drop_column(u'app_user', 'residence_id')
    op.drop_column(u'app_user', 'nationality_id')
    op.drop_column(u'app_user', 'lastname')
    op.drop_column(u'app_user', 'is_deleted')
    op.drop_column(u'app_user', 'firstname')
    op.drop_column(u'app_user', 'department')
    op.drop_column(u'app_user', 'deleted_datetime_utc')
    op.drop_column(u'app_user', 'affiliation')
    op.drop_table('user_title')
    op.drop_table('user_gender')
    op.drop_table('user_ethnicity')
    op.drop_table('user_disability')
    op.drop_table('user_category')
    op.drop_table('country')
    # ### end Alembic commands ###
