"""Add allows_edits column to application_form table

Revision ID: 7fb62ea19309
Revises: 2162b7b3d69c
Create Date: 2025-08-30 15:53:33.048838

"""

# revision identifiers, used by Alembic.
revision = '7fb62ea19309'
down_revision = '2162b7b3d69c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('allows_edits', sa.Boolean(), nullable=True))
    op.execute("UPDATE application_form SET allows_edits = True;")
    op.alter_column('application_form', 'allows_edits', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_form', 'allows_edits')
    # ### end Alembic commands ###
