"""empty message

Revision ID: 7fced3d22209
Revises: 2873f4f08a4b
Create Date: 2020-01-22 14:26:45.992225

"""

# revision identifiers, used by Alembic.
revision = '7fced3d22209'
down_revision = '2873f4f08a4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_user', 'affiliation',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('app_user', 'department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('app_user', 'nationality_country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('app_user', 'residence_country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('app_user', 'user_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('app_user', 'user_disability',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('app_user', 'user_gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_user', 'user_gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('app_user', 'user_disability',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('app_user', 'user_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('app_user', 'residence_country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('app_user', 'nationality_country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('app_user', 'department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('app_user', 'affiliation',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
