"""Made AppUser fields nullable

Revision ID: 7fced3d22209
Revises: 32c1ae6dd23a
Create Date: 2020-01-22 14:26:45.992225

"""

# revision identifiers, used by Alembic.
revision = "7fced3d22209"
down_revision = "32c1ae6dd23a"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_user", "affiliation", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "app_user", "department", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "app_user", "nationality_country_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "app_user", "residence_country_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "app_user", "user_category_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "app_user",
        "user_disability",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "app_user", "user_gender", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_user", "user_gender", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "app_user",
        "user_disability",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "app_user", "user_category_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "app_user", "residence_country_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "app_user", "nationality_country_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "app_user", "department", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "app_user", "affiliation", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
