"""empty message

Revision ID: 80f82bd50600
Revises: 351c26992f23
Create Date: 2019-01-22 19:45:45.718275

"""

# revision identifiers, used by Alembic.
revision = '80f82bd50600'
down_revision = '351c26992f23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    country = op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_category = op.create_table('user_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    user_disability = op.create_table('user_disability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_ethnicity = op.create_table('user_ethnicity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_gender = op.create_table('user_gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_title = op.create_table('user_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'app_user', sa.Column('affiliation', sa.String(length=255), nullable=False))
    op.add_column(u'app_user', sa.Column('deleted_datetime_utc', sa.DateTime(), nullable=True))
    op.add_column(u'app_user', sa.Column('department', sa.String(length=255), nullable=False))
    op.add_column(u'app_user', sa.Column('firstname', sa.String(length=100), nullable=False))
    op.add_column(u'app_user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column(u'app_user', sa.Column('lastname', sa.String(length=100), nullable=False))
    op.add_column(u'app_user', sa.Column('nationality_country_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('residence_country_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_category_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_disability_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_ethnicity_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_gender_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_title_id', sa.Integer(), nullable=False))
    op.alter_column(u'app_user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column(u'app_user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'app_user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column(u'app_user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(u'app_user_residence_country_id', 'app_user', 'country', ['residence_country_id'], ['id'])
    op.create_foreign_key(u'app_user_user_title_id', 'app_user', 'user_title', ['user_title_id'], ['id'])
    op.create_foreign_key(u'app_user_nationality_country_id', 'app_user', 'country', ['nationality_country_id'], ['id'])
    op.create_foreign_key(u'app_user_user_gender_id', 'app_user', 'user_gender', ['user_gender_id'], ['id'])
    op.create_foreign_key(u'app_user_user_category_id', 'app_user', 'user_category', ['user_category_id'], ['id'])
    op.create_foreign_key(u'app_user_user_ethnicity_id', 'app_user', 'user_ethnicity', ['user_ethnicity_id'], ['id'])
    op.create_foreign_key(u'app_user_user_disability_id', 'app_user', 'user_disability', ['user_disability_id'], ['id'])
    # ### end Alembic commands ###
    seed_user_titles(op, user_title)
    seed_user_genders(op, user_gender)
    seed_user_ethnicities(op, user_ethnicity)
    seed_user_disabilities(op, user_disability)
    seed_user_categories(op, user_category)
    seed_countries(op, country)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'app_user_residence_country_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_title_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_nationality_country_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_gender_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_category_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_ethnicity_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_disability_id', 'app_user', type_='foreignkey')
    op.alter_column(u'app_user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'app_user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column(u'app_user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'app_user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column(u'app_user', 'user_title_id')
    op.drop_column(u'app_user', 'user_gender_id')
    op.drop_column(u'app_user', 'user_ethnicity_id')
    op.drop_column(u'app_user', 'user_disability_id')
    op.drop_column(u'app_user', 'user_category_id')
    op.drop_column(u'app_user', 'residence_country_id')
    op.drop_column(u'app_user', 'nationality_country_id')
    op.drop_column(u'app_user', 'lastname')
    op.drop_column(u'app_user', 'is_deleted')
    op.drop_column(u'app_user', 'firstname')
    op.drop_column(u'app_user', 'department')
    op.drop_column(u'app_user', 'deleted_datetime_utc')
    op.drop_column(u'app_user', 'affiliation')
    op.drop_table('user_title')
    op.drop_table('user_gender')
    op.drop_table('user_ethnicity')
    op.drop_table('user_disability')
    op.drop_table('user_category')
    op.drop_table('country')
    # ### end Alembic commands ###


def seed_user_titles(op, user_title):
    op.bulk_insert(user_title, [
        {'name': 'Prof'},
        {'name': 'Dr'},
        {'name': 'Mr'},
        {'name': 'Ms'},
        {'name': 'Mx'}
    ])

def seed_user_genders(op, user_gender):
    op.bulk_insert(user_gender, [
        {'name': 'Female'},
        {'name': 'Male'},
        {'name': 'Prefer not to say'}
    ])

def seed_user_ethnicities(op, user_ethnicity):
    op.bulk_insert(user_ethnicity, [
        {'name': 'Black'},
        {'name': 'Coloured/mixed descent'},
        {'name': 'White'},
        {'name': 'Indian'}
    ])

def seed_user_disabilities(op, user_disability):
    op.bulk_insert(user_disability, [
        {'name': 'No disabilities'},
        {'name': 'Sight disability'},
        {'name': 'Hearing disability'},
        {'name': 'Communication disability'},
        {'name': 'Physical disability (e.g. difficulty in walking)'},
        {'name': 'Mental disability (e.g. difficulty in remembering or concentrating)'},
        {'name': 'Difficulty in self-care'}
    ])

def seed_user_categories(op, user_category):
    op.bulk_insert(user_category, [
        {'name': '4th year/honours student'},
        {'name': 'Student at a coding academy/institute'},
        {'name': 'MSc student'},
        {'name': 'PhD student'},
        {'name': 'Postdoc'},
        {'name': 'Academic'},
        {'name': 'Industry professional'},
        {'name': 'Mentor Attendee (By Invitation)'}
    ])

def seed_countries(op, country):
    op.bulk_insert(country, [
        {'name': 'Afghanistan'},
        {'name': 'Akrotiri'},
        {'name': 'Albania'},
        {'name': 'Algeria'},
        {'name': 'American Samoa'},
        {'name': 'Andorra'},
        {'name': 'Angola'},
        {'name': 'Anguilla'},
        {'name': 'Antarctica'},
        {'name': 'Antigua and Barbuda'},
        {'name': 'Argentina'},
        {'name': 'Armenia'},
        {'name': 'Aruba'},
        {'name': 'Ashmore and Cartier Islands'},
        {'name': 'Australia'},
        {'name': 'Austria'},
        {'name': 'Azerbaijan'},
        {'name': 'Bahamas, The'},
        {'name': 'Bahrain'},
        {'name': 'Bangladesh'},
        {'name': 'Barbados'},
        {'name': 'Bassas da India'},
        {'name': 'Belarus'},
        {'name': 'Belgium'},
        {'name': 'Belize'},
        {'name': 'Benin'},
        {'name': 'Bermuda'},
        {'name': 'Bhutan'},
        {'name': 'Bolivia'},
        {'name': 'Bosnia and Herzegovina'},
        {'name': 'Botswana'},
        {'name': 'Bouvet Island'},
        {'name': 'Brazil'},
        {'name': 'British Indian Ocean Territory'},
        {'name': 'British Virgin Islands'},
        {'name': 'Brunei'},
        {'name': 'Bulgaria'},
        {'name': 'Burkina Faso'},
        {'name': 'Burma'},
        {'name': 'Burundi'},
        {'name': 'Cambodia'},
        {'name': 'Cameroon'},
        {'name': 'Canada'},
        {'name': 'Cape Verde'},
        {'name': 'Cayman Islands'},
        {'name': 'Central African Republic'},
        {'name': 'Chad'},
        {'name': 'Chile'},
        {'name': 'China'},
        {'name': 'Christmas Island'},
        {'name': 'Clipperton Island'},
        {'name': 'Cocos (Keeling) Islands'},
        {'name': 'Colombia'},
        {'name': 'Comoros'},
        {'name': 'Congo, Democratic Republic of the'},
        {'name': 'Congo, Republic of the'},
        {'name': 'Cook Islands'},
        {'name': 'Coral Sea Islands'},
        {'name': 'Costa Rica'},
        {'name': 'Cote d\'Ivoire'},
        {'name': 'Croatia'},
        {'name': 'Cuba'},
        {'name': 'Cyprus'},
        {'name': 'Czech Republic'},
        {'name': 'Denmark'},
        {'name': 'Dhekelia'},
        {'name': 'Djibouti'},
        {'name': 'Dominica'},
        {'name': 'Dominican Republic'},
        {'name': 'Ecuador'},
        {'name': 'Egypt'},
        {'name': 'El Salvador'},
        {'name': 'Equatorial Guinea'},
        {'name': 'Eritrea'},
        {'name': 'Estonia'},
        {'name': 'Ethiopia'},
        {'name': 'Europa Island'},
        {'name': 'Falkland Islands (Islas Malvinas)'},
        {'name': 'Faroe Islands'},
        {'name': 'Fiji'},
        {'name': 'Finland'},
        {'name': 'France'},
        {'name': 'French Guiana'},
        {'name': 'French Polynesia'},
        {'name': 'French Southern and Antarctic Lands'},
        {'name': 'Gabon'},
        {'name': 'Gambia, The'},
        {'name': 'Gaza Strip'},
        {'name': 'Georgia'},
        {'name': 'Germany'},
        {'name': 'Ghana'},
        {'name': 'Gibraltar'},
        {'name': 'Glorioso Islands'},
        {'name': 'Greece'},
        {'name': 'Greenland'},
        {'name': 'Grenada'},
        {'name': 'Guadeloupe'},
        {'name': 'Guam'},
        {'name': 'Guatemala'},
        {'name': 'Guernsey'},
        {'name': 'Guinea'},
        {'name': 'Guinea-Bissau'},
        {'name': 'Guyana'},
        {'name': 'Haiti'},
        {'name': 'Heard Island and McDonald Islands'},
        {'name': 'Holy See (Vatican City)'},
        {'name': 'Honduras'},
        {'name': 'Hong Kong'},
        {'name': 'Hungary'},
        {'name': 'Iceland'},
        {'name': 'India'},
        {'name': 'Indonesia'},
        {'name': 'Iran'},
        {'name': 'Iraq'},
        {'name': 'Ireland'},
        {'name': 'Isle of Man'},
        {'name': 'Israel'},
        {'name': 'Italy'},
        {'name': 'Jamaica'},
        {'name': 'Jan Mayen'},
        {'name': 'Japan'},
        {'name': 'Jersey'},
        {'name': 'Jordan'},
        {'name': 'Juan de Nova Island'},
        {'name': 'Kazakhstan'},
        {'name': 'Kenya'},
        {'name': 'Kiribati'},
        {'name': 'Korea, North'},
        {'name': 'Korea, South'},
        {'name': 'Kuwait'},
        {'name': 'Kyrgyzstan'},
        {'name': 'Laos'},
        {'name': 'Latvia'},
        {'name': 'Lebanon'},
        {'name': 'Lesotho'},
        {'name': 'Liberia'},
        {'name': 'Libya'},
        {'name': 'Liechtenstein'},
        {'name': 'Lithuania'},
        {'name': 'Luxembourg'},
        {'name': 'Macau'},
        {'name': 'Macedonia'},
        {'name': 'Madagascar'},
        {'name': 'Malawi'},
        {'name': 'Malaysia'},
        {'name': 'Maldives'},
        {'name': 'Mali'},
        {'name': 'Malta'},
        {'name': 'Marshall Islands'},
        {'name': 'Martinique'},
        {'name': 'Mauritania'},
        {'name': 'Mauritius'},
        {'name': 'Mayotte'},
        {'name': 'Mexico'},
        {'name': 'Micronesia, Federated States of'},
        {'name': 'Moldova'},
        {'name': 'Monaco'},
        {'name': 'Mongolia'},
        {'name': 'Montenegro'},
        {'name': 'Montserrat'},
        {'name': 'Morocco'},
        {'name': 'Mozambique'},
        {'name': 'Namibia'},
        {'name': 'Nauru'},
        {'name': 'Navassa Island'},
        {'name': 'Nepal'},
        {'name': 'Netherlands'},
        {'name': 'Netherlands Antilles'},
        {'name': 'New Caledonia'},
        {'name': 'New Zealand'},
        {'name': 'Nicaragua'},
        {'name': 'Niger'},
        {'name': 'Nigeria'},
        {'name': 'Niue'},
        {'name': 'Norfolk Island'},
        {'name': 'Northern Mariana Islands'},
        {'name': 'Norway'},
        {'name': 'Oman'},
        {'name': 'Pakistan'},
        {'name': 'Palau'},
        {'name': 'Panama'},
        {'name': 'Papua New Guinea'},
        {'name': 'Paracel Islands'},
        {'name': 'Paraguay'},
        {'name': 'Peru'},
        {'name': 'Philippines'},
        {'name': 'Pitcairn Islands'},
        {'name': 'Poland'},
        {'name': 'Portugal'},
        {'name': 'Puerto Rico'},
        {'name': 'Qatar'},
        {'name': 'Reunion'},
        {'name': 'Romania'},
        {'name': 'Russia'},
        {'name': 'Rwanda'},
        {'name': 'Saint Helena'},
        {'name': 'Saint Kitts and Nevis'},
        {'name': 'Saint Lucia'},
        {'name': 'Saint Pierre and Miquelon'},
        {'name': 'Saint Vincent and the Grenadines'},
        {'name': 'Samoa'},
        {'name': 'San Marino'},
        {'name': 'Sao Tome and Principe'},
        {'name': 'Saudi Arabia'},
        {'name': 'Senegal'},
        {'name': 'Serbia'},
        {'name': 'Seychelles'},
        {'name': 'Sierra Leone'},
        {'name': 'Singapore'},
        {'name': 'Slovakia'},
        {'name': 'Slovenia'},
        {'name': 'Solomon Islands'},
        {'name': 'Somalia'},
        {'name': 'South Africa'},
        {'name': 'South Georgia and the South Sandwich Islands'},
        {'name': 'South Sudan'},
        {'name': 'Spain'},
        {'name': 'Spratly Islands'},
        {'name': 'Sri Lanka'},
        {'name': 'Sudan'},
        {'name': 'Suriname'},
        {'name': 'Svalbard'},
        {'name': 'Swaziland'},
        {'name': 'Sweden'},
        {'name': 'Switzerland'},
        {'name': 'Syria'},
        {'name': 'Taiwan'},
        {'name': 'Tajikistan'},
        {'name': 'Tanzania'},
        {'name': 'Thailand'},
        {'name': 'Timor-Leste'},
        {'name': 'Togo'},
        {'name': 'Tokelau'},
        {'name': 'Tonga'},
        {'name': 'Trinidad and Tobago'},
        {'name': 'Tromelin Island'},
        {'name': 'Tunisia'},
        {'name': 'Turkey'},
        {'name': 'Turkmenistan'},
        {'name': 'Turks and Caicos Islands'},
        {'name': 'Tuvalu'},
        {'name': 'Uganda'},
        {'name': 'Ukraine'},
        {'name': 'United Arab Emirates'},
        {'name': 'United Kingdom'},
        {'name': 'United States'},
        {'name': 'Uruguay'},
        {'name': 'Uzbekistan'},
        {'name': 'Vanuatu'},
        {'name': 'Venezuela'},
        {'name': 'Vietnam'},
        {'name': 'Virgin Islands'},
        {'name': 'Wake Island'},
        {'name': 'Wallis and Futuna'},
        {'name': 'West Bank'},
        {'name': 'Western Sahara'},
        {'name': 'Yemen'},
        {'name': 'Zambia'},
        {'name': 'Zimbabwe'}
    ])