"""empty message

Revision ID: 80f82bd50600
Revises: 351c26992f23
Create Date: 2019-01-22 19:45:45.718275

"""

# revision identifiers, used by Alembic.
revision = '80f82bd50600'
down_revision = '351c26992f23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    country = op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_category = op.create_table('user_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    user_disability = op.create_table('user_disability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_ethnicity = op.create_table('user_ethnicity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_gender = op.create_table('user_gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_title = op.create_table('user_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'app_user', sa.Column('affiliation', sa.String(length=255), nullable=False))
    op.add_column(u'app_user', sa.Column('deleted_datetime_utc', sa.DateTime(), nullable=True))
    op.add_column(u'app_user', sa.Column('department', sa.String(length=255), nullable=False))
    op.add_column(u'app_user', sa.Column('firstname', sa.String(length=100), nullable=False))
    op.add_column(u'app_user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column(u'app_user', sa.Column('lastname', sa.String(length=100), nullable=False))
    op.add_column(u'app_user', sa.Column('nationality_country_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('residence_country_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_category_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_disability_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_ethnicity_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_gender_id', sa.Integer(), nullable=False))
    op.add_column(u'app_user', sa.Column('user_title_id', sa.Integer(), nullable=False))
    op.alter_column(u'app_user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column(u'app_user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'app_user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column(u'app_user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(u'app_user_residence_country_id', 'app_user', 'country', ['residence_country_id'], ['id'])
    op.create_foreign_key(u'app_user_user_title_id', 'app_user', 'user_title', ['user_title_id'], ['id'])
    op.create_foreign_key(u'app_user_nationality_country_id', 'app_user', 'country', ['nationality_country_id'], ['id'])
    op.create_foreign_key(u'app_user_user_gender_id', 'app_user', 'user_gender', ['user_gender_id'], ['id'])
    op.create_foreign_key(u'app_user_user_category_id', 'app_user', 'user_category', ['user_category_id'], ['id'])
    op.create_foreign_key(u'app_user_user_ethnicity_id', 'app_user', 'user_ethnicity', ['user_ethnicity_id'], ['id'])
    op.create_foreign_key(u'app_user_user_disability_id', 'app_user', 'user_disability', ['user_disability_id'], ['id'])
    # ### end Alembic commands ###
    seed_user_titles(op, user_title)
    seed_user_genders(op, user_gender)
    seed_user_ethnicities(op, user_ethnicity)
    seed_user_disabilities(op, user_disability)
    seed_user_categories(op, user_category)
    seed_countries(op, country)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'app_user_residence_country_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_title_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_nationality_country_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_gender_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_category_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_ethnicity_id', 'app_user', type_='foreignkey')
    op.drop_constraint(u'app_user_user_disability_id', 'app_user', type_='foreignkey')
    op.alter_column(u'app_user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'app_user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column(u'app_user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'app_user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column(u'app_user', 'user_title_id')
    op.drop_column(u'app_user', 'user_gender_id')
    op.drop_column(u'app_user', 'user_ethnicity_id')
    op.drop_column(u'app_user', 'user_disability_id')
    op.drop_column(u'app_user', 'user_category_id')
    op.drop_column(u'app_user', 'residence_country_id')
    op.drop_column(u'app_user', 'nationality_country_id')
    op.drop_column(u'app_user', 'lastname')
    op.drop_column(u'app_user', 'is_deleted')
    op.drop_column(u'app_user', 'firstname')
    op.drop_column(u'app_user', 'department')
    op.drop_column(u'app_user', 'deleted_datetime_utc')
    op.drop_column(u'app_user', 'affiliation')
    op.drop_table('user_title')
    op.drop_table('user_gender')
    op.drop_table('user_ethnicity')
    op.drop_table('user_disability')
    op.drop_table('user_category')
    op.drop_table('country')
    # ### end Alembic commands ###


def seed_user_titles(op, user_title):
    op.bulk_insert(user_title, [
        {'id': 1, 'name': 'Prof'},
        {'id': 2, 'name': 'Dr'},
        {'id': 3, 'name': 'Mr'},
        {'id': 4, 'name': 'Ms'},
        {'id': 5, 'name': 'Mx'}
    ])

def seed_user_genders(op, user_gender):
    op.bulk_insert(user_gender, [
        {'id': 1,'name': 'Female'},
        {'id': 2,'name': 'Male'},
        {'id': 3,'name': 'Prefer not to say'}
    ])

def seed_user_ethnicities(op, user_ethnicity):
    op.bulk_insert(user_ethnicity, [
        {'id': 1,'name': 'Black'},
        {'id': 2,'name': 'Coloured/mixed descent'},
        {'id': 3,'name': 'White'},
        {'id': 4,'name': 'Indian'}
    ])

def seed_user_disabilities(op, user_disability):
    op.bulk_insert(user_disability, [
        {'id': 1,'name': 'No disabilities'},
        {'id': 2,'name': 'Sight disability'},
        {'id': 3,'name': 'Hearing disability'},
        {'id': 4,'name': 'Communication disability'},
        {'id': 5,'name': 'Physical disability (e.g. difficulty in walking)'},
        {'id': 6,'name': 'Mental disability (e.g. difficulty in remembering or concentrating)'},
        {'id': 7,'name': 'Difficulty in self-care'}
    ])

def seed_user_categories(op, user_category):
    op.bulk_insert(user_category, [
        {'id': 1,'name': '4th year/honours student'},
        {'id': 2,'name': 'Student at a coding academy/institute'},
        {'id': 3,'name': 'MSc student'},
        {'id': 4,'name': 'PhD student'},
        {'id': 5,'name': 'Postdoc'},
        {'id': 6,'name': 'Academic'},
        {'id': 7,'name': 'Industry professional'},
        {'id': 8,'name': 'Mentor Attendee (By Invitation)'}
    ])

def seed_countries(op, country):
    op.bulk_insert(country, [
        {'id': 1, 'name': 'Afghanistan'},
        {'id': 2, 'name': 'Akrotiri'},
        {'id': 3, 'name': 'Albania'},
        {'id': 4, 'name': 'Algeria'},
        {'id': 5, 'name': 'American Samoa'},
        {'id': 6, 'name': 'Andorra'},
        {'id': 7, 'name': 'Angola'},
        {'id': 8, 'name': 'Anguilla'},
        {'id': 9, 'name': 'Antarctica'},
        {'id': 10, 'name': 'Antigua and Barbuda'},
        {'id': 11, 'name': 'Argentina'},
        {'id': 12, 'name': 'Armenia'},
        {'id': 13, 'name': 'Aruba'},
        {'id': 14, 'name': 'Ashmore and Cartier Islands'},
        {'id': 15, 'name': 'Australia'},
        {'id': 16, 'name': 'Austria'},
        {'id': 17, 'name': 'Azerbaijan'},
        {'id': 18, 'name': 'Bahamas, The'},
        {'id': 19, 'name': 'Bahrain'},
        {'id': 20, 'name': 'Bangladesh'},
        {'id': 21, 'name': 'Barbados'},
        {'id': 22, 'name': 'Bassas da India'},
        {'id': 23, 'name': 'Belarus'},
        {'id': 24, 'name': 'Belgium'},
        {'id': 25, 'name': 'Belize'},
        {'id': 26, 'name': 'Benin'},
        {'id': 27, 'name': 'Bermuda'},
        {'id': 28, 'name': 'Bhutan'},
        {'id': 29, 'name': 'Bolivia'},
        {'id': 30, 'name': 'Bosnia and Herzegovina'},
        {'id': 31, 'name': 'Botswana'},
        {'id': 32, 'name': 'Bouvet Island'},
        {'id': 33, 'name': 'Brazil'},
        {'id': 34, 'name': 'British Indian Ocean Territory'},
        {'id': 35, 'name': 'British Virgin Islands'},
        {'id': 36, 'name': 'Brunei'},
        {'id': 37, 'name': 'Bulgaria'},
        {'id': 38, 'name': 'Burkina Faso'},
        {'id': 39, 'name': 'Burma'},
        {'id': 40, 'name': 'Burundi'},
        {'id': 41, 'name': 'Cambodia'},
        {'id': 42, 'name': 'Cameroon'},
        {'id': 43, 'name': 'Canada'},
        {'id': 44, 'name': 'Cape Verde'},
        {'id': 45, 'name': 'Cayman Islands'},
        {'id': 46, 'name': 'Central African Republic'},
        {'id': 47, 'name': 'Chad'},
        {'id': 48, 'name': 'Chile'},
        {'id': 49, 'name': 'China'},
        {'id': 50, 'name': 'Christmas Island'},
        {'id': 51, 'name': 'Clipperton Island'},
        {'id': 52, 'name': 'Cocos (Keeling) Islands'},
        {'id': 53, 'name': 'Colombia'},
        {'id': 54, 'name': 'Comoros'},
        {'id': 55, 'name': 'Congo, Democratic Republic of the'},
        {'id': 56, 'name': 'Congo, Republic of the'},
        {'id': 57, 'name': 'Cook Islands'},
        {'id': 58, 'name': 'Coral Sea Islands'},
        {'id': 59, 'name': 'Costa Rica'},
        {'id': 60, 'name': 'Cote d\'Ivoire'},
        {'id': 61, 'name': 'Croatia'},
        {'id': 62, 'name': 'Cuba'},
        {'id': 63, 'name': 'Cyprus'},
        {'id': 64, 'name': 'Czech Republic'},
        {'id': 65, 'name': 'Denmark'},
        {'id': 66, 'name': 'Dhekelia'},
        {'id': 67, 'name': 'Djibouti'},
        {'id': 68, 'name': 'Dominica'},
        {'id': 69, 'name': 'Dominican Republic'},
        {'id': 70, 'name': 'Ecuador'},
        {'id': 71, 'name': 'Egypt'},
        {'id': 72, 'name': 'El Salvador'},
        {'id': 73, 'name': 'Equatorial Guinea'},
        {'id': 74, 'name': 'Eritrea'},
        {'id': 75, 'name': 'Estonia'},
        {'id': 76, 'name': 'Ethiopia'},
        {'id': 77, 'name': 'Europa Island'},
        {'id': 78, 'name': 'Falkland Islands (Islas Malvinas)'},
        {'id': 79, 'name': 'Faroe Islands'},
        {'id': 80, 'name': 'Fiji'},
        {'id': 81, 'name': 'Finland'},
        {'id': 82, 'name': 'France'},
        {'id': 83, 'name': 'French Guiana'},
        {'id': 84, 'name': 'French Polynesia'},
        {'id': 85, 'name': 'French Southern and Antarctic Lands'},
        {'id': 86, 'name': 'Gabon'},
        {'id': 87, 'name': 'Gambia, The'},
        {'id': 88, 'name': 'Gaza Strip'},
        {'id': 89, 'name': 'Georgia'},
        {'id': 90, 'name': 'Germany'},
        {'id': 91, 'name': 'Ghana'},
        {'id': 92, 'name': 'Gibraltar'},
        {'id': 93, 'name': 'Glorioso Islands'},
        {'id': 94, 'name': 'Greece'},
        {'id': 95, 'name': 'Greenland'},
        {'id': 96, 'name': 'Grenada'},
        {'id': 97, 'name': 'Guadeloupe'},
        {'id': 98, 'name': 'Guam'},
        {'id': 99, 'name': 'Guatemala'},
        {'id': 100, 'name': 'Guernsey'},
        {'id': 101, 'name': 'Guinea'},
        {'id': 102, 'name': 'Guinea-Bissau'},
        {'id': 103, 'name': 'Guyana'},
        {'id': 104, 'name': 'Haiti'},
        {'id': 105, 'name': 'Heard Island and McDonald Islands'},
        {'id': 106, 'name': 'Holy See (Vatican City)'},
        {'id': 107, 'name': 'Honduras'},
        {'id': 108, 'name': 'Hong Kong'},
        {'id': 109, 'name': 'Hungary'},
        {'id': 110, 'name': 'Iceland'},
        {'id': 111, 'name': 'India'},
        {'id': 112, 'name': 'Indonesia'},
        {'id': 113, 'name': 'Iran'},
        {'id': 114, 'name': 'Iraq'},
        {'id': 115, 'name': 'Ireland'},
        {'id': 116, 'name': 'Isle of Man'},
        {'id': 117, 'name': 'Israel'},
        {'id': 118, 'name': 'Italy'},
        {'id': 119, 'name': 'Jamaica'},
        {'id': 120, 'name': 'Jan Mayen'},
        {'id': 121, 'name': 'Japan'},
        {'id': 122, 'name': 'Jersey'},
        {'id': 123, 'name': 'Jordan'},
        {'id': 124, 'name': 'Juan de Nova Island'},
        {'id': 125, 'name': 'Kazakhstan'},
        {'id': 126, 'name': 'Kenya'},
        {'id': 127, 'name': 'Kiribati'},
        {'id': 128, 'name': 'Korea, North'},
        {'id': 129, 'name': 'Korea, South'},
        {'id': 130, 'name': 'Kuwait'},
        {'id': 131, 'name': 'Kyrgyzstan'},
        {'id': 132, 'name': 'Laos'},
        {'id': 133, 'name': 'Latvia'},
        {'id': 134, 'name': 'Lebanon'},
        {'id': 135, 'name': 'Lesotho'},
        {'id': 136, 'name': 'Liberia'},
        {'id': 137, 'name': 'Libya'},
        {'id': 138, 'name': 'Liechtenstein'},
        {'id': 139, 'name': 'Lithuania'},
        {'id': 140, 'name': 'Luxembourg'},
        {'id': 141, 'name': 'Macau'},
        {'id': 142, 'name': 'Macedonia'},
        {'id': 143, 'name': 'Madagascar'},
        {'id': 144, 'name': 'Malawi'},
        {'id': 145, 'name': 'Malaysia'},
        {'id': 146, 'name': 'Maldives'},
        {'id': 147, 'name': 'Mali'},
        {'id': 148, 'name': 'Malta'},
        {'id': 149, 'name': 'Marshall Islands'},
        {'id': 150, 'name': 'Martinique'},
        {'id': 151, 'name': 'Mauritania'},
        {'id': 152, 'name': 'Mauritius'},
        {'id': 153, 'name': 'Mayotte'},
        {'id': 154, 'name': 'Mexico'},
        {'id': 155, 'name': 'Micronesia, Federated States of'},
        {'id': 156, 'name': 'Moldova'},
        {'id': 157, 'name': 'Monaco'},
        {'id': 158, 'name': 'Mongolia'},
        {'id': 159, 'name': 'Montenegro'},
        {'id': 160, 'name': 'Montserrat'},
        {'id': 161, 'name': 'Morocco'},
        {'id': 162, 'name': 'Mozambique'},
        {'id': 163, 'name': 'Namibia'},
        {'id': 164, 'name': 'Nauru'},
        {'id': 165, 'name': 'Navassa Island'},
        {'id': 166, 'name': 'Nepal'},
        {'id': 167, 'name': 'Netherlands'},
        {'id': 168, 'name': 'Netherlands Antilles'},
        {'id': 169, 'name': 'New Caledonia'},
        {'id': 170, 'name': 'New Zealand'},
        {'id': 171, 'name': 'Nicaragua'},
        {'id': 172, 'name': 'Niger'},
        {'id': 173, 'name': 'Nigeria'},
        {'id': 174, 'name': 'Niue'},
        {'id': 175, 'name': 'Norfolk Island'},
        {'id': 176, 'name': 'Northern Mariana Islands'},
        {'id': 177, 'name': 'Norway'},
        {'id': 178, 'name': 'Oman'},
        {'id': 179, 'name': 'Pakistan'},
        {'id': 180, 'name': 'Palau'},
        {'id': 181, 'name': 'Panama'},
        {'id': 182, 'name': 'Papua New Guinea'},
        {'id': 183, 'name': 'Paracel Islands'},
        {'id': 184, 'name': 'Paraguay'},
        {'id': 185, 'name': 'Peru'},
        {'id': 186, 'name': 'Philippines'},
        {'id': 187, 'name': 'Pitcairn Islands'},
        {'id': 188, 'name': 'Poland'},
        {'id': 189, 'name': 'Portugal'},
        {'id': 190, 'name': 'Puerto Rico'},
        {'id': 191, 'name': 'Qatar'},
        {'id': 192, 'name': 'Reunion'},
        {'id': 193, 'name': 'Romania'},
        {'id': 194, 'name': 'Russia'},
        {'id': 195, 'name': 'Rwanda'},
        {'id': 196, 'name': 'Saint Helena'},
        {'id': 197, 'name': 'Saint Kitts and Nevis'},
        {'id': 198, 'name': 'Saint Lucia'},
        {'id': 199, 'name': 'Saint Pierre and Miquelon'},
        {'id': 200, 'name': 'Saint Vincent and the Grenadines'},
        {'id': 201, 'name': 'Samoa'},
        {'id': 202, 'name': 'San Marino'},
        {'id': 203, 'name': 'Sao Tome and Principe'},
        {'id': 204, 'name': 'Saudi Arabia'},
        {'id': 205, 'name': 'Senegal'},
        {'id': 206, 'name': 'Serbia'},
        {'id': 207, 'name': 'Seychelles'},
        {'id': 208, 'name': 'Sierra Leone'},
        {'id': 209, 'name': 'Singapore'},
        {'id': 210, 'name': 'Slovakia'},
        {'id': 211, 'name': 'Slovenia'},
        {'id': 212, 'name': 'Solomon Islands'},
        {'id': 213, 'name': 'Somalia'},
        {'id': 214, 'name': 'South Africa'},
        {'id': 215, 'name': 'South Georgia and the South Sandwich Islands'},
        {'id': 216, 'name': 'South Sudan'},
        {'id': 217, 'name': 'Spain'},
        {'id': 218, 'name': 'Spratly Islands'},
        {'id': 219, 'name': 'Sri Lanka'},
        {'id': 220, 'name': 'Sudan'},
        {'id': 221, 'name': 'Suriname'},
        {'id': 222, 'name': 'Svalbard'},
        {'id': 223, 'name': 'Swaziland'},
        {'id': 224, 'name': 'Sweden'},
        {'id': 225, 'name': 'Switzerland'},
        {'id': 226, 'name': 'Syria'},
        {'id': 227, 'name': 'Taiwan'},
        {'id': 228, 'name': 'Tajikistan'},
        {'id': 229, 'name': 'Tanzania'},
        {'id': 230, 'name': 'Thailand'},
        {'id': 231, 'name': 'Timor-Leste'},
        {'id': 232, 'name': 'Togo'},
        {'id': 233, 'name': 'Tokelau'},
        {'id': 234, 'name': 'Tonga'},
        {'id': 235, 'name': 'Trinidad and Tobago'},
        {'id': 236, 'name': 'Tromelin Island'},
        {'id': 237, 'name': 'Tunisia'},
        {'id': 238, 'name': 'Turkey'},
        {'id': 239, 'name': 'Turkmenistan'},
        {'id': 240, 'name': 'Turks and Caicos Islands'},
        {'id': 241, 'name': 'Tuvalu'},
        {'id': 242, 'name': 'Uganda'},
        {'id': 243, 'name': 'Ukraine'},
        {'id': 244, 'name': 'United Arab Emirates'},
        {'id': 245, 'name': 'United Kingdom'},
        {'id': 246, 'name': 'United States'},
        {'id': 247, 'name': 'Uruguay'},
        {'id': 248, 'name': 'Uzbekistan'},
        {'id': 249, 'name': 'Vanuatu'},
        {'id': 250, 'name': 'Venezuela'},
        {'id': 251, 'name': 'Vietnam'},
        {'id': 252, 'name': 'Virgin Islands'},
        {'id': 253, 'name': 'Wake Island'},
        {'id': 254, 'name': 'Wallis and Futuna'},
        {'id': 255, 'name': 'West Bank'},
        {'id': 256, 'name': 'Western Sahara'},
        {'id': 257, 'name': 'Yemen'},
        {'id': 258, 'name': 'Zambia'},
        {'id': 259, 'name': 'Zimbabwe'}
    ])