"""Set depends_on_question_id to NULL on Section when that question is deleted

Revision ID: 81526c9dbb6f
Revises: 2ae07ae036c1
Create Date: 2024-04-02 19:45:41.199800

"""

# revision identifiers, used by Alembic.
revision = '81526c9dbb6f'
down_revision = '2ae07ae036c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('section_depends_on_question_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key('section_depends_on_question_id_fkey', 'section', 'question', ['depends_on_question_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('section_depends_on_question_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key('section_depends_on_question_id_fkey', 'section', 'question', ['depends_on_question_id'], ['id'])
    # ### end Alembic commands ###
