# -*- coding: utf-8 -*-

"""Small AI4D Update

Revision ID: 8339a70d7345
Revises: cb503c2afd08
Create Date: 2020-09-20 21:28:41.262559

"""

# revision identifiers, used by Alembic.
revision = '8339a70d7345'
down_revision = 'cb503c2afd08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.execute("""update question_translation set headline='Website (Optional)' where headline='Website'""")
    op.execute("""update question_translation set headline='Social media handles (Optional)' where headline='Social media handles'""")
    op.execute(u"""update question_translation set headline='Pseudonymes sur les médias sociaux (facultatif)' where headline='Pseudonymes sur les médias sociaux'""")
    op.execute(u"""update question_translation set headline='Site Web (facultatif)' where headline='Site Web'""")
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
