"""empty message

Revision ID: 85d13062a5e7
Revises: d80784e674a8
Create Date: 2020-02-25 18:22:20.037572

"""

# revision identifiers, used by Alembic.
revision = "85d13062a5e7"
down_revision = "d80784e674a8"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "response", sa.Column("nomination_email", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "response",
        sa.Column("nomination_firstname", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "response",
        sa.Column("nomination_lastname", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "response", sa.Column("nomination_title", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("response", "nomination_title")
    op.drop_column("response", "nomination_lastname")
    op.drop_column("response", "nomination_firstname")
    op.drop_column("response", "nomination_email")
    # ### end Alembic commands ###
