"""empty message

Revision ID: 878f67285c72
Revises: 122dd6a5c035
Create Date: 2019-05-29 12:57:36.544059

"""

# revision identifiers, used by Alembic.
revision = '878f67285c72'
down_revision = '122dd6a5c035'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ###commandsautogeneratedbyAlembic-pleaseadjust!###
    op.create_table('registration',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('offer_id', sa.Integer(), nullable=False),
                    sa.Column('registration_form_id', sa.Integer(), nullable=False),
                    sa.Column('confirmed', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('confirmation_email_sent_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['offer_id'], ['offer.id']),
                    sa.ForeignKeyConstraint(['registration_form_id'], ['registration_form.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('registration_answer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('registration_id', sa.Integer(), nullable=False),
                    sa.Column('registration_question_id', sa.Integer(), nullable=False),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['registration_id'], ['registration.id']),
                    sa.ForeignKeyConstraint(['registration_question_id'], ['registration_question.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ###endAlembiccommands###


def downgrade():
    # ### commands auto generated by Alembic-please adjust!###
    op.drop_table('registration')
    op.drop_table('registration_answer')
    # ###endAlembiccommands###
