"""empty message

Revision ID: 8a1468838847
Revises: 99f650dc0924
Create Date: 2019-03-25 09:31:25.626164

"""

# revision identifiers, used by Alembic.
revision = '8a1468838847'
down_revision = '99f650dc0924'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_reviewer', sa.Column('reviewer_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('response_reviewer_user_id_fkey', 'response_reviewer', type_='foreignkey')
    op.create_foreign_key('response_reviewer_reviewer_user_id_fkey', 'response_reviewer', 'app_user', ['reviewer_user_id'], ['id'])
    op.drop_column('response_reviewer', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_reviewer', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('response_reviewer_reviewer_user_id_fkey', 'response_reviewer', type_='foreignkey')
    op.create_foreign_key('response_reviewer_user_id_fkey', 'response_reviewer', 'app_user', ['user_id'], ['id'])
    op.drop_column('response_reviewer', 'reviewer_user_id')
    # ### end Alembic commands ###
