"""empty message

Revision ID: 8ba06d0a54ee
Revises: 0023aeda53b0
Create Date: 2020-02-14 07:13:05.049933

"""

# revision identifiers, used by Alembic.
revision = '8ba06d0a54ee'
down_revision = '0023aeda53b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
