"""empty message

Revision ID: 8ba06d0a54ee
Revises: 0023aeda53b0
Create Date: 2020-02-14 07:13:05.049933

"""

# revision identifiers, used by Alembic.
revision = "8ba06d0a54ee"
down_revision = "0023aeda53b0"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
