"""add event_resource_link and event timezone checkin_mode

Revision ID: 8bfeebfbdf01
Revises: d2b3c4e5f6a7
Create Date: 2026-06-14 17:57:54.950318

"""

# revision identifiers, used by Alembic.
revision = '8bfeebfbdf01'
down_revision = 'd2b3c4e5f6a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_resource_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=160), nullable=False),
    sa.Column('title_fr', sa.String(length=160), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_resource_link')
    # ### end Alembic commands ###
