"""empty message

Revision ID: 91468f804113
Revises: 0ab2d6bca67d
Create Date: 2019-03-14 16:44:53.740564

"""

# revision identifiers, used by Alembic.
revision = '91468f804113'
down_revision = '0ab2d6bca67d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'user_ethnicity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('user_ethnicity', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
