"""Add language to response

Revision ID: 984cb348ec98
Revises: 297276d57414
Create Date: 2020-08-11 12:41:57.931661

"""

# revision identifiers, used by Alembic.
revision = "984cb348ec98"
down_revision = "297276d57414"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("response", sa.Column("language", sa.String(length=2), nullable=True))
    op.execute("""UPDATE response SET language='en'""")
    op.alter_column("response", "language", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("response", "language")
    # ### end Alembic commands ###
