"""empty message

Revision ID: 99cfdad9869c
Revises: 7fced3d22209
Create Date: 2020-01-27 07:19:34.448207

"""

# revision identifiers, used by Alembic.
revision = "99cfdad9869c"
down_revision = "7fced3d22209"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "org_email_unique", "app_user", ["email", "organisation_id"]
    )
    op.drop_constraint("app_user_email_key", "app_user", type_="unique")
    op.alter_column(
        "organisation",
        "system_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organisation",
        "system_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.create_unique_constraint("app_user_email_key", "app_user", ["email"])
    op.drop_constraint("org_email_unique", "app_user", type_="unique")
    # ### end Alembic commands ###
