"""Add outcome model

Revision ID: a4662031beca
Revises: 492546998537
Create Date: 2020-04-11 17:23:44.894509

"""

# revision identifiers, used by Alembic.
revision = 'a4662031beca'
down_revision = '492546998537'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

outcome_status = postgresql.ENUM('ACCEPTED', 'REJECTED', 'WAITLIST', name='outcome_status')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'REJECTED', 'WAITLIST', name='outcome_status'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latest', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome')
    outcome_status.drop(op.get_bind())
    # ### end Alembic commands ###
