"""Add question dependencies in registration form.

Revision ID: a5480ca6646b
Revises: 472bf293e0a1
Create Date: 2019-06-20 21:27:05.714614

"""

# revision identifiers, used by Alembic.
revision = "a5480ca6646b"
down_revision = "472bf293e0a1"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registration_question",
        sa.Column("depends_on_question_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "registration_question",
        sa.Column("hide_for_dependent_value", sa.String(), nullable=True),
    )
    op.add_column(
        "registration_question", sa.Column("required_value", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "registration_question",
        "registration_question",
        ["depends_on_question_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "registration_question", type_="foreignkey")
    op.drop_column("registration_question", "required_value")
    op.drop_column("registration_question", "hide_for_dependent_value")
    op.drop_column("registration_question", "depends_on_question_id")
    # ### end Alembic commands ###
