"""empty message

Revision ID: a5876b93baee
Revises: aa890a74c772
Create Date: 2019-05-28 12:57:17.856544

"""

# revision identifiers, used by Alembic.
revision = 'a5876b93baee'
down_revision = 'aa890a74c772'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration_question', 'validation_regex', nullable=True)
    op.alter_column('registration_question', 'validation_text', nullable=True)
    op.alter_column('registration_question', 'options', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration_question', 'validation_regex', nullable=False)
    op.alter_column('registration_question', 'validation_text', nullable=False)
    op.alter_column('registration_question', 'options', nullable=False)
    # ### end Alembic commands ###
