"""empty message

Revision ID: a83fa2500452
Revises: b7006cbdd923
Create Date: 2020-01-29 15:25:30.694663

"""

# revision identifiers, used by Alembic.
revision = 'a83fa2500452'
down_revision = 'b7006cbdd923'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

from app.email_template.models import EmailTemplate


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    email_template = table(
        'email_template',
        column('id', sa.Integer()),
        column('key', sa.String(50)),
        column('event_id', sa.Integer()),
        column('template', sa.String())
    )

    op.bulk_insert(
        email_template,
        [
            {
                'id': 1,
                'key': 'attendance-welcome',
                'event_id': None,
                'template': """Dear {user_title} {first_name} {last_name},

Welcome to the {event_name}! We're so excited that you made it.

If you have any questions or issues, please chat to one of the organisers wearing RED t-shirts, post a message on the Slack group or email us at info@deeplearningindaba.com.

Kind Regards,
The {organisation_name} Team"""
            },
            {
                'id': 2,
                'key': 'application-not-submitted',
                'event_id': None,
                'template': """
Dear {title} {firstname} {lastname},

We noticed that you started applying to attend the {event} but have not completed and submitted your application. This is a final reminder that you have until {deadline} to submit your application in order to be considered. Please complete and submit your application if you would still like to attend this event.

We have noticed that some people were confused about the "check your answers" page and may not have clicked on the Submit button on this page. Please be aware that you must click on the Submit button to confirm your application. If you do not receive an email from us with a copy of your answers, your application will not be considered.

Kind Regards,
The {organisation_name} team
"""
            },
            {
                'id': 3,
                'key': 'application-not-started',
                'event_id': None,
                'template': """
Dear {title} {firstname} {lastname},

WE HAVE NOT RECEIVED YOUR APPLICATION TO ATTEND {event}

We noticed that you have created a {system_name} account, but have not yet started an application to attend {event}.

If you think you have already filled in the form, you may have not clicked on the SUBMIT button on the final page. If this is the case, we DO NOT have your application and unfortunately you will have to re-do it. We sincerely apologise for any confusion and inconvenience in this regard.
This is a final reminder that you have until {deadline} to complete and submit your application.

Please ensure you have submitted your application before this date if you would still like to attend this event.

Kind Regards,
The {organisation_name} team
"""
            },
            {
                'id': 4,
                'key': 'guest-invite',
                'event_id': None,
                'template': """Dear {user_title} {firstname} {lastname},

We are pleased to invite you to attend the {organisation_name} as a {role}. 
To assist with our planning process, please complete our guest registration form in {system_name}, by visiting {host}/registration 
After completing this, you will also be able to generate an official invitation letter, should you require one for visa or other purposes.

Please reply to this email should you have any questions or concerns.  

Kind Regards,
The {organisation_name} Organising Committee
"""
            },
            {
                'id': 5,
                'key': 'new-guest-invite',
                'event_id': None,
                'template': """Dear {user_title} {firstname} {lastname},

We are pleased to invite you to attend the {organisation_name} as a {role}. 
To assist with our planning process, please complete our guest registration form in our portal, {system_name}, by following these instructions:

1. Visit {host}/resetPassword?resetToken={reset_code} to set your account password.
2. Log in using your email address (the one you received this email on!) and new password.
3. Visit {host}/registration to complete the registration form.
4. Update your user profile by visiting {host}/profile - while this step is optional, we highly value this data for reporting purposes! 

After completing the registration form, you will also be able to generate an official invitation letter, should you require one for visa or other purposes.

Please reply to this email should you have any questions or concerns. 

Kind Regards,
The {organisation_name} Organising Committee
"""
            },
            {
                'id': 6,
                'key': 'offer',
                'event_id': None,
                'template': """
Dear {user_title} {first_name} {last_name},

Congratulations! You've been selected to attend the {event_name}!

Please follow the link below to see details and accept your offer: {host}/offer
You have up until the {expiry_date} to accept the offer, otherwise we will automatically allocate your spot to someone else.

If you are unable to accept the offer for any reason, please do let us know by visiting {host}/offer, clicking "Reject" and filling in the reason. 
We will read all of these and if there is anything we can do to accommodate you (for example if more funding for travel becomes available), we may extend you a new offer in a subsequent round.

If you have any queries, please forward them to info@deeplearningindaba.com  

Kind Regards,
The {organisation_name} Team
"""
            },
            {
                'id': 7,
                'key': 'withdrawal',
                'event_id': None,
                'template': """Dear {title} {firstname} {lastname},

This email serves to confirm that you have withdrawn your application to attend the Deep Learning Indaba 2019. 

If this was a mistake, you may resubmit an application before the application deadline. If the deadline has past, please get in touch with us.

Kind Regards,
The {organisation_name} Team
"""
            }
        ]
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
