"""empty message

Revision ID: aa890a74c772
Revises: 3745cf17152b
Create Date: 2019-05-28 09:47:37.597920

"""

# revision identifiers, used by Alembic.
revision = 'aa890a74c772'
down_revision = '3745cf17152b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('registration_form',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['event.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('registration_section',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('registration_form_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.Column('show_for_travel_award', sa.Boolean(), nullable=False),
                    sa.Column('show_for_accommodation_award', sa.Boolean(), nullable=False),
                    sa.Column('show_for_payment_required', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['registration_form_id'], ['registration_form.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('registration_question',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('registration_form_id', sa.Integer(), nullable=False),
                    sa.Column('section_id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('headline', sa.String(), nullable=False),
                    sa.Column('placeholder', sa.String(), nullable=False),
                    sa.Column('validation_regex', sa.String(), nullable=False),
                    sa.Column('validation_text', sa.String(), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.Column('options', sa.JSON(), nullable=False),
                    sa.Column('is_required', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['registration_form_id'], ['registration_form.id']),
                    sa.ForeignKeyConstraint(['section_id'], ['registration_section.id']),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_question')
    op.drop_table('registration_section')
    op.drop_table('registration_form')

    # ### end Alembic commands ###
