"""empty message

Revision ID: ae7c72f05201
Revises: 1cdf3a2cf02b
Create Date: 2023-04-05 00:23:31.627506

"""

# revision identifiers, used by Alembic.
revision = 'ae7c72f05201'
down_revision = '1cdf3a2cf02b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'active')
    # ### end Alembic commands ###
