import sqlalchemy as sa
from alembic import op
"""empty message

Revision ID: ae94d067a229
Revises: f2cefa124236
Create Date: 2019-07-05 16:10:37.947773

"""

# revision identifiers, used by Alembic.
revision = 'ae94d067a229'
down_revision = 'f2cefa124236'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation_letter_request', sa.Column(
        'guest_registration_id', sa.Integer(), nullable=True))
    op.alter_column('invitation_letter_request', 'registration_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('invitation_letter_request', 'work_address',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.create_foreign_key(None, 'invitation_letter_request', 'guest_registration', [
                          'guest_registration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'invitation_letter_request_registration_id_fkey',
                       'invitation_letter_request', type_='foreignkey')
    op.alter_column('invitation_letter_request', 'work_address',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('invitation_letter_request', 'registration_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_column('invitation_letter_request', 'guest_registration_id')
    # ### end Alembic commands ###
