"""empty message

Revision ID: b3f7a73c98f3
Revises: 38dde1052c5e
Create Date: 2019-01-27 15:00:09.209537

"""

# revision identifiers, used by Alembic.
revision = 'b3f7a73c98f3'
down_revision = '38dde1052c5e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    application_form = op.create_table('application_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'])
    )

    section = op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_form_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_form.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    question = op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_form_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(), nullable = True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable = True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_form.id']),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'] ),
    sa.PrimaryKeyConstraint('id'),
    )

    seed_application_form_data(application_form)
    seed_section_data(section)
    seed_question_data(question)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('section')
    op.drop_table('application_form')
    # ### end Alembic commands ###

def seed_application_form_data(application_form):
    op.bulk_insert(application_form,
    [
        {
            'id': 1,
            'event_id': 1,
            'is_open': True,
            'deadline': '30 April 2019'
        }
    ])

def seed_section_data(section):
    op.bulk_insert(section,
    [
        {
            'id': 1,
            'application_form_id': 1,
            'name': 'Indaba 2019 Application Form',
            'description': 'This is the official application form to apply for participation in the Deep Learning Indaba to be held 25-31 August 2019 in Nairobi, Kenya. Students can also use this application form to apply for travel and accommodation awards. \n \n \n Closing date: 30 April 2019',
            'order': 1            
        },
        {
            'id': 2,
            'application_form_id': 1,
            'name': 'Tell Us a Bit About You',
            'description': 'Please use this section to tell us a bit more about yourself and your intentions as a future Deep Learning Indaba ambassador.',
            'order': 2            
        },
        {
            'id': 3,
            'application_form_id': 1,
            'name': 'Apply For Travel Support ',
            'description': 'We may be able to sponsor the cost of travel and accommodation for some attendees. These travel awards are limited and highly competitive, but are assessed independently of Indaba attendance: applying for a travel award neither enhances nor undermines your chances of being accepted. To help as many people attend as possible, before applying for travel support, please check if your supervisor, department or university is able to support you in any way. ',
            'order': 3            
        },
        {
            'id': 4,
            'application_form_id': 1,
            'name': 'Demographic Information',
            'description': 'We regard the promotion of diversity, inclusivity and transformation as a high priority. The information below helps us track our progress in this regard.',
            'order': 4            
        },
        {
            'id': 5,
            'application_form_id': 1,
            'name': 'Previous Attendance',
            'description': 'Help us quantify our progress by giving us some info on your previous Indaba experiences.',
            'order': 5            
        },
        {
            'id': 6,
            'application_form_id': 1,
            'name': 'Additional Information',
            'description': 'Anything else you may want us to know',
            'order': 6           
        }
    ])

def seed_question_data(question):
    op.bulk_insert(question,
    [
        {
            'id': 1,
            'application_form_id': 1,
            'section_id': 2,
            'type': 'long_text',
            'headline': 'Why is attending the Deep Learning Indaba 2019 important to you?',
            'description': 'Provide a paragraph of 50-150 words.',
            'order': 1,
            'is_required': True,  
            'options': None           
        },
        {
            'id': 2,
            'application_form_id': 1,
            'section_id': 2,
            'type': 'long_text',
            'headline': 'How will you share what you have learnt after the Indaba?',
            'description': 'Provide a paragraph of 50-150 words.',
            'order': 2,
            'is_required': True,  
            'options': None           
        },
        {
            'id': 3,
            'application_form_id': 1,
            'section_id': 2,
            'type': 'long_text',
            'headline': 'Share with us a favourite machine learning resource you use: a paper, blog post, algorithm, result, or finding. Tell us why.',
            'description': 'Maximum 80 words.',
            'order': 3,
            'is_required': True,  
            'options': None           
        },
        {
            'id': 4,
            'application_form_id': 1,
            'section_id': 2,
            'type': 'long_text',
            'headline': 'Are you or have you been a tutor for any relevant course, or part of any machine learning or data science society or meetup? If yes, give details.',
            'description': 'Maximum 80 words.',
            'order': 4,
            'is_required': True,  
            'options': None           
        },
        {
            'id': 5,
            'application_form_id': 1,
            'section_id': 2,
            'type': 'long_text',
            'headline': 'Have you worked on a project that uses machine learning? If yes, give a short description.',
            'description': 'Maximum 150 words.',
            'order': 5,
            'is_required': False,  
            'options': None           
        },
        {
            'id': 6,
            'application_form_id': 1,
            'section_id': 2,
            'type': 'file',
            'headline': 'Please upload your CV (pdf, max size 10MB)',
            'description': 'We generally do not look at CVs, but ask for this so that we can make a more informed selection, if needed.',
            'order': 6,
            'is_required': True,  
            'options': None           
        },
        {
            'id': 7,
            'application_form_id': 1,
            'section_id': 2,
            'type': 'multi-choice',
            'headline': 'May we add your CV and email address to a database for sharing with our sponsors?',
            'description': 'If you are accepted, we would like to add your CV and email address to a database. We will share this database with our sponsors (only) so they may get in touch with you about events, internships, job openings, grants and scholarships, etc. We think you will find this useful in exploring future career options. Click yes if you would like us to add your CV and email address to this database (no other information from your application will be included).' ,
            'order': 7,
            'is_required': True,
            'options': [
                {'selection': 'Yes'},
                {'selection': 'No'}
            ]     
        },
        {
            'id': 8,
            'application_form_id': 1,
            'section_id': 3,
            'type': 'multi-choice',
            'headline': 'Would you like to be considered for a travel award?',
            'description': 'Travel awards will be used to cover the costs of return flights to the host city, as well as accommodation in shared dorm rooms close to the venue.',
            'order': 1,
            'is_required': True,    
            'options': [
                {'selection': 'Yes, transport and accomodation'},
                {'selection': 'Yes, transport only'},
                {'selection': 'Yes, accommodation only'},
                {'selection': 'No'}
            ]     
        },
        {
            'id': 9,
            'application_form_id': 1,
            'section_id': 3,
            'type': 'long-text',
            'headline': 'If you selected yes, please provide a short motivation for why you should be considered for a travel award.',
            'description': 'Maximum 150 words.',
            'order': 2,
            'is_required': False,  
            'options': None           
        },
        {
            'id': 10,
            'application_form_id': 1,
            'section_id': 3,
            'type': 'short-text',
            'headline': 'If you selected yes to an award including transport, please state the intended airport of departure.',
            'order': 3,
            'description': None,
            'is_required': False,  
            'options': None           
        },
        {
            'id': 11,
            'application_form_id': 1,
            'section_id': 3,
            'type': 'multi-choice',
            'headline': 'If you do not receive a travel award from us, will you still be able to attend?',
            'order': 4,
            'description': None,
            'is_required': False,
            'options': [
                {'selection': 'Yes'},
                {'selection': 'No'}
            ]     
        },
        {
            'id': 12,
            'application_form_id': 1,
            'section_id': 4,
            'type': 'multi-choice',
            'headline': 'Gender',
            'order': 1,
            'description': None,
            'is_required': True,
            'options': [
                {'selection': 'Female'},
                {'selection': 'Male'},
                {'selection': 'Prefer not to say'}
            ]     
        },
        {
            'id': 13,
            'application_form_id': 1,
            'section_id': 4,
            'type': 'multi-choice',
            'headline': 'Ethnicity',
            'description': 'We use South African demographic groupings for reporting.',
            'order': 2,
            'is_required': True,
            'options': [
                {'selection': 'Black'},
                {'selection': 'Coloured / Mixed Descent'},
                {'selection': 'White'},
                {'selection': 'Indian Descent'},
                {'selection': 'Other'}
            ]     
        },
        {
            'id': 14,
            'application_form_id': 1,
            'section_id': 4,
            'type': 'multi-choice',
            'headline': 'Do you have any disability?',
            'description': 'We use the Washington Group difficulty schemes, and it helps us to ensure that our facilities can accommodate the needs of all attendees.',
            'order': 3,
            'is_required': True,
            'options': [
                {'selection': 'No disabilities'},
                {'selection': 'Sight disability'},
                {'selection': 'Hearing disability'},
                {'selection': 'Communication disability'},
                {'selection': 'Physical disability (e.g. difficulty in walking)'},
                {'selection': 'Mental disability (e.g. difficulty in remembering or concentrating)'},
                {'selection': 'Difficulty in self-care'},
                {'selection': 'Other'}
            ]     
        },
        {
            'id': 15,
            'application_form_id': 1,
            'section_id': 5,
            'type': 'multi-choice',
            'headline': 'Did you attend the 2017 or 2018 Indaba',
            'order': 1,
            'description': None,
            'is_required': True,
            'options': [
                {'selection': 'Yes, I attended the 2017 Indaba'},
                {'selection': 'Yes, I attended the 2018 Indaba'},
                {'selection': 'Yes, I attended both Indabas'},
                {'selection': 'No'}
            ]      
        },
        {
            'id': 16,
            'application_form_id': 1,
            'section_id': 5,
            'type': 'long-text',
            'headline': 'If you attended a previous Indaba, tell us how it has helped you grow or how you have used what you have learnt.',
            'order': 2,
            'description': None,
            'is_required': False,  
            'options': None        
        },
        {
            'id': 17,
            'application_form_id': 1,
            'section_id': 6,
            'type': 'long-text',
            'headline': 'Any additional comments or remarks for the selection committee?',
            'order': 1,
            'description': None,
            'is_required': False,  
            'options': None        
        },
        {
            'id': 18,
            'application_form_id': 1,
            'section_id': 6,
            'type': 'long-text',
            'headline': 'Anything else you think relevant, for example links to personal webpage, papers, GitHub/code repositories, community and outreach activities. ',
            'description': 'Maximum 150 words.',
            'order': 2,
            'is_required': False,  
            'options': None        
        }
    ])


