"""empty message

Revision ID: b7006cbdd923
Revises: 32c1ae6dd23a
Create Date: 2020-01-26 22:09:30.227267

"""

# revision identifiers, used by Alembic.
revision = 'b7006cbdd923'
down_revision = '3bc5355f159c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('application_close', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('application_open', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('offer_close', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('offer_open', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('registration_close', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('registration_open', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('review_close', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('review_open', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('selection_close', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('selection_open', sa.DateTime(), nullable=True))

    op.execute("""
    UPDATE event 
    SET 
        application_open = '2019-03-01',
        application_close = '2019-04-30',
        review_open = '2019-05-01',
        review_close = '2019-05-31',
        selection_open = '2019-06-01',
        selection_close = '2019-06-30',
        offer_open = '2019-07-01',
        offer_close = '2019-07-14',
        registration_open = '2019-07-15',
        registration_close = '2019-07-31'
    WHERE id = 1""")

    op.alter_column('event', 'application_close', nullable=False)
    op.alter_column('event', 'application_open', nullable=False)
    op.alter_column('event', 'offer_close', nullable=False)
    op.alter_column('event', 'offer_open', nullable=False)
    op.alter_column('event', 'registration_close', nullable=False)
    op.alter_column('event', 'registration_open', nullable=False)
    op.alter_column('event', 'review_close', nullable=False)
    op.alter_column('event', 'review_open', nullable=False)
    op.alter_column('event', 'selection_close', nullable=False)
    op.alter_column('event', 'selection_open', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'selection_open')
    op.drop_column('event', 'selection_close')
    op.drop_column('event', 'review_open')
    op.drop_column('event', 'review_close')
    op.drop_column('event', 'registration_open')
    op.drop_column('event', 'registration_close')
    op.drop_column('event', 'offer_open')
    op.drop_column('event', 'offer_close')
    op.drop_column('event', 'application_open')
    op.drop_column('event', 'application_close')
    # ### end Alembic commands ###
