"""empty message

Revision ID: b7006cbdd923
Revises: 32c1ae6dd23a
Create Date: 2020-01-26 22:09:30.227267

"""

# revision identifiers, used by Alembic.
revision = 'b7006cbdd923'
down_revision = '3bc5355f159c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('org_email_unique', 'app_user', ['email', 'organisation_id'])
    op.drop_constraint(u'app_user_email_key', 'app_user', type_='unique')
    op.add_column('event', sa.Column('application_close', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('application_open', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('offer_close', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('offer_open', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('registration_close', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('registration_open', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('review_close', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('review_open', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('selection_close', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('selection_open', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'selection_open')
    op.drop_column('event', 'selection_close')
    op.drop_column('event', 'review_open')
    op.drop_column('event', 'review_close')
    op.drop_column('event', 'registration_open')
    op.drop_column('event', 'registration_close')
    op.drop_column('event', 'offer_open')
    op.drop_column('event', 'offer_close')
    op.drop_column('event', 'application_open')
    op.drop_column('event', 'application_close')
    op.create_unique_constraint(u'app_user_email_key', 'app_user', ['email'])
    op.drop_constraint('org_email_unique', 'app_user', type_='unique')
    # ### end Alembic commands ###
