"""empty message

Revision ID: ba1e64272aa
Revises: 351c26992f23
Create Date: 2019-01-08 14:58:25.549348

"""

# revision identifiers, used by Alembic.
revision = 'ba1e64272aa'
down_revision = '351c26992f23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'unique_user_code', 'password_reset')
    op.drop_index('unique_user_code', table_name='password_reset')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_user_code', 'password_reset', ['user_id', 'code'], unique=True)
    op.create_unique_constraint(u'unique_user_code', 'password_reset', ['user_id', 'code'])
    ### end Alembic commands ###
