"""empty message

Revision ID: c06c236ad4c5
Revises: 539d0567cd6c
Create Date: 2019-06-14 06:45:09.307238

"""

# revision identifiers, used by Alembic.
revision = "c06c236ad4c5"
down_revision = "539d0567cd6c"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offer", sa.Column("candidate_response", sa.Boolean(), nullable=True))
    op.add_column("offer", sa.Column("responded_at", sa.DateTime(), nullable=False))
    op.drop_column("offer", "accepted")
    op.drop_column("offer", "updated_at")
    op.drop_column("offer", "rejected")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offer",
        sa.Column(
            "rejected", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "offer",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "offer", sa.Column("accepted", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_column("offer", "responded_at")
    op.drop_column("offer", "candidate_response")
    # ### end Alembic commands ###
