"""empty message

Revision ID: c0885e531d29
Revises: 878f67285c72
Create Date: 2019-06-06 10:24:01.869322

"""

# revision identifiers, used by Alembic.
revision = 'c0885e531d29'
down_revision = '878f67285c72'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('accommodation_award', sa.Boolean(), nullable=True))
    op.add_column('offer', sa.Column('payment_required', sa.Boolean(), nullable=False))
    op.drop_column('offer', 'payement_required')
    op.drop_column('offer', 'accomodation_award')
    op.drop_column('offer', 'accepted')
    op.alter_column('registration', 'confirmation_email_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('registration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('registration', 'confirmation_email_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('offer', sa.Column('accepted', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('accomodation_award', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('payement_required', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('offer', 'payment_required')
    op.drop_column('offer', 'accommodation_award')
    # ### end Alembic commands ###
