"""empty message

Revision ID: c56a126e3ee4
Revises: 016571f41a20
Create Date: 2020-02-06 12:17:05.552012

"""

# revision identifiers, used by Alembic.
revision = 'c56a126e3ee4'
down_revision = '016571f41a20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
