"""Add stripe API key columns

Revision ID: c5a76ae67dd0
Revises: 69c2778c27cb
Create Date: 2022-06-04 16:03:05.164975

"""

# revision identifiers, used by Alembic.
revision = 'c5a76ae67dd0'
down_revision = '69c2778c27cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('stripe_api_publishable_key', sa.String(length=200), nullable=True))
    op.add_column('organisation', sa.Column('stripe_api_secret_key', sa.String(length=200), nullable=True))
    op.add_column('organisation', sa.Column('stripe_webhook_secret_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'stripe_webhook_secret_key')
    op.drop_column('organisation', 'stripe_api_secret_key')
    op.drop_column('organisation', 'stripe_api_publishable_key')
    # ### end Alembic commands ###
