"""empty message

Revision ID: c77955079fba
Revises: b6c743c9e6ff
Create Date: 2020-02-11 18:15:45.529322

"""

# revision identifiers, used by Alembic.
revision = 'c77955079fba'
down_revision = 'b6c743c9e6ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('policy_agreed_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'policy_agreed_datetime')
    # ### end Alembic commands ###
