"""empty message

Revision ID: c79ebe42885e
Revises: 5d5b0524b4fa
Create Date: 2023-05-31 19:41:12.771834

"""

# revision identifiers, used by Alembic.
revision = 'c79ebe42885e'
down_revision = '5d5b0524b4fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
