"""empty message

Revision ID: d2b59c9f33c3
Revises: 3ec3ed0eb3c6
Create Date: 2020-04-11 16:20:50.917621

"""

# revision identifiers, used by Alembic.
revision = 'd2b59c9f33c3'
down_revision = '3ec3ed0eb3c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'nomination_email')
    op.drop_column('response', 'nomination_firstname')
    op.drop_column('response', 'nomination_title')
    op.drop_column('response', 'nomination_lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('nomination_lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_title', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_firstname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('nomination_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
