"""empty message

Revision ID: d2c160b0cbe5
Revises: fb6d5f943621
Create Date: 2024-09-16 08:42:06.110593

"""

# revision identifiers, used by Alembic.
revision = 'd2c160b0cbe5'
down_revision = 'fb6d5f943621'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column('reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'reason')
    # ### end Alembic commands ###
