"""empty message

Revision ID: d2e49e3c0fed
Revises: 0b9cc856acbb
Create Date: 2025-02-19 20:24:04.572029

"""

# revision identifiers, used by Alembic.
revision = 'd2e49e3c0fed'
down_revision = '0b9cc856acbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcome', 'review_summary',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcome', 'review_summary',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
