"""empty message

Revision ID: e622c3deea5d
Revises: b7006cbdd923
Create Date: 2020-01-30 06:58:43.897538

"""

# revision identifiers, used by Alembic.
revision = "e622c3deea5d"
down_revision = "b7006cbdd923"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("response_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("firstname", sa.String(length=50), nullable=False),
        sa.Column("lastname", sa.String(length=50), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=False),
        sa.Column("token", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("email_sent", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["response.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reference_request")
    # ### end Alembic commands ###
