"""empty message

Revision ID: eac3fd9d5ae8
Revises: 865b2e2d02ff
Create Date: 2019-07-04 10:15:47.711795

"""


# revision identifiers, used by Alembic.
revision = "eac3fd9d5ae8"
down_revision = "865b2e2d02ff"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guest_registration",
        "confirmation_email_sent_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "guest_registration",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("invitation_letter_request", "invitation_letter_sent_at")
    op.add_column(
        "invitation_letter_request",
        sa.Column("invitation_letter_sent_at", sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guest_registration",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "guest_registration",
        "confirmation_email_sent_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )

    op.drop_column("invitation_letter_request", "invitation_letter_sent_at")
    op.add_column(
        "invitation_letter_request",
        sa.Column("invitation_letter_sent_at", sa.String(), nullable=False),
    )

    # ### end Alembic commands ###
