"""empty message

Revision ID: f349debf9e15
Revises: 88199ece9b26
Create Date: 2019-07-02 10:20:47.871312

"""

# revision identifiers, used by Alembic.
revision = 'f349debf9e15'
down_revision = '88199ece9b26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation_letter_request', sa.Column('passport_expiry_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation_letter_request', 'passport_expiry_date')
    # ### end Alembic commands ###
