"""Add event indemnity.

Revision ID: f4402dcafde3
Revises: 02089e6b336b
Create Date: 2022-08-13 15:17:18.208336

"""

# revision identifiers, used by Alembic.
revision = 'f4402dcafde3'
down_revision = '02089e6b336b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_indemnity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('indemnity_form', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attendance', sa.Column('indemnity_signed', sa.Boolean(), nullable=False))
    op.add_column('attendance', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'confirmed')
    op.drop_column('attendance', 'indemnity_signed')
    op.drop_table('event_indemnity')
    # ### end Alembic commands ###
