"""empty message

Revision ID: f4bc3108c330
Revises: 2717ef90a874
Create Date: 2020-02-29 14:33:22.682384

"""

# revision identifiers, used by Alembic.
revision = "f4bc3108c330"
down_revision = "2717ef90a874"

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
