"""empty message

Revision ID: f8ab033698a2
Revises: 37fbee2da7b7
Create Date: 2020-02-12 16:53:57.726270

"""

# revision identifiers, used by Alembic.
revision = "f8ab033698a2"
down_revision = "37fbee2da7b7"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_form", sa.Column("nominations", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE application_form SET nominations = false")
    op.alter_column("application_form", "nominations", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application_form", "nominations")
    # ### end Alembic commands ###
