"""empty message

Revision ID: f8ab033698a2
Revises: 0023aeda53b0
Create Date: 2020-02-12 16:53:57.726270

"""

# revision identifiers, used by Alembic.
revision = 'f8ab033698a2'
down_revision = '0023aeda53b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('nominations', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_form', 'nominations')
    # ### end Alembic commands ###
