"""empty message

Revision ID: f906472c4ec4
Revises: 3c1062e77427
Create Date: 2019-05-28 19:36:14.943564

"""

# revision identifiers, used by Alembic.
revision = 'f906472c4ec4'
down_revision = '3c1062e77427'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
