"""empty message

Revision ID: f9da9ad6b174
Revises: 3447b1bb8210
Create Date: 2024-10-08 08:49:03.542714

"""

# revision identifiers, used by Alembic.
revision = 'f9da9ad6b174'
down_revision = '3447b1bb8210'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = inspector.get_columns('response')
    if 'parent_id' not in [c['name'] for c in columns]:
        op.add_column('response', sa.Column('parent_id', sa.Integer(), nullable=True))
    
    # Check if the foreign key constraint already exists
    constraints = inspector.get_foreign_keys('response')
    if not any(constraint['name'] == 'fk_response_parent_id' for constraint in constraints):
        op.create_foreign_key('fk_response_parent_id', 'response', 'response', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint('fk_response_parent_id', 'response', type_='foreignkey')
    except Exception:
        # If the constraint doesn't exist, we can ignore this error
        pass

    try:
        op.drop_column('response', 'parent_id')
    except Exception:
        # If the column doesn't exist, we can ignore this error
        pass
    # ### end Alembic commands ###
