"""empty message

Revision ID: f9e34f59d257
Revises: 0d063877a565
Create Date: 2022-06-22 14:19:39.318327

"""

# revision identifiers, used by Alembic.
revision = 'f9e34f59d257'
down_revision = '0d063877a565'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_payment_status', 'created_at_unix', type_=sa.FLOAT())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_payment_status', 'created_at_unix', type_=sa.INTEGER())
    # ### end Alembic commands ###
