"""empty message

Revision ID: fbd283484655
Revises: 6fa47605c615
Create Date: 2019-02-22 17:19:17.510033

"""

# revision identifiers, used by Alembic.
revision = 'fbd283484655'
down_revision = '6fa47605c615'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from app.applicationModel.models import Question


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_code', table_name='password_reset')
    op.add_column('question', sa.Column('placeholder', sa.String(), nullable=True))
    op.add_column('question', sa.Column('validation_regex', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'section', ['order'])
    update_question_data()
    # ### end Alembic commands ###

def update_question(session, question_id, placeholder, validation_regex):
    question = session.query(Question).filter(Question.id == question_id).first()
    question.placeholder = placeholder
    question.validation_regex = validation_regex

def update_question_data():
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    update_question(session, 1, 'Enter 50 to 150 words', r'^\W*(\w+(\W+|$)){50,150}$')
    update_question(session, 2, 'Enter 50 to 150 words', r'^\W*(\w+(\W+|$)){50,150}$')
    update_question(session, 3, 'Enter up to 80 words, remember to include *why*', r'^\W*(\w+(\W+|$)){0,80}$')
    update_question(session, 4, 'Enter up to 80 words', r'^\W*(\w+(\W+|$)){0,80}$')
    update_question(session, 5, 'Enter up to 150 words', r'^\W*(\w+(\W+|$)){0,150}$')
    update_question(session, 7, 'Select an option...', None)
    update_question(session, 8, 'Select an option...', None)
    update_question(session, 9, 'Enter up to 150 words', r'^\W*(\w+(\W+|$)){0,150}$')
    update_question(session, 10, 'Departure Airport', None)
    update_question(session, 11, 'Select an option...', None)
    update_question(session, 12, 'Select an option...', None)
    update_question(session, 13, 'Select an option...', None)
    update_question(session, 14, 'Select an option...', None)
    update_question(session, 15, 'Select an option...', None)
    update_question(session, 18, 'Enter up to 150 words', r'^\W*(\w+(\W+|$)){0,150}$')

    grow_question = session.query(Question).filter(Question.id == 16).first()
    grow_question.placeholder = 'Enter up to 150 words'
    grow_question.validation_regex = r'^\W*(\w+(\W+|$)){0,150}$'
    grow_question.description = 'Maximum 150 words.'

    session.commit()
    session.flush()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='unique')
    op.drop_column('question', 'validation_regex')
    op.drop_column('question', 'placeholder')
    op.create_index('unique_user_code', 'password_reset', ['user_id', 'code'], unique=True)
    # ### end Alembic commands ###
