"""Add show_for_invited_guest to registration section

Revision ID: fd232b2eed5e
Revises: 794506c08e10
Create Date: 2022-05-22 15:57:17.280490

"""

# revision identifiers, used by Alembic.
revision = 'fd232b2eed5e'
down_revision = '794506c08e10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_section', sa.Column('show_for_invited_guest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_section', 'show_for_invited_guest')
    # ### end Alembic commands ###
