service: prod-frontend
runtime: python312

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|pdf|json)(|\.map))$
    static_files: build/\1
    upload: build/(.*)(|\.map)
    secure: always
    redirect_http_response_code: 301

  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
