service: staging-api
runtime: python
env: flex
entrypoint: gunicorn -c gunicorn.config.py -b :$PORT main:app

runtime_config:
    python_version: 2

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  DATABASE_URL: 'postgres://postgres:postgres@35.239.114.17/staging'
  SECRET_KEY: '4321'  
  SMTP_USERNAME: "dummy"
  SMTP_PASSWORD: "dummy"
  SMTP_SENDER_NAME: "dummy"
  SMTP_SENDER_EMAIL: "dummy"
  SMTP_HOST: "dummy"
  SMTP_PORT: "dummy"