FROM python:3.11-slim

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends locales \
    && locale-gen en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN pip install --upgrade pip

ADD requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

ADD . /app
WORKDIR /app

CMD gunicorn -c gunicorn.config.py -b :$PORT main:app
